import { ChangeDetectorRef, ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { MatMenuTrigger } from '@angular/material/menu';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { TranslateService } from '@ngx-translate/core';
import { JobFilter, JobStatus, JobType } from '@shared/models/job.model';
import { EntityType } from '@shared/models/entity-type.models';
import * as i0 from "@angular/core";
export declare class TaskManagerFilterComponent implements OnInit, ControlValueAccessor {
    private fb;
    private translate;
    private cd;
    filterMenuTrigger: MatMenuTrigger;
    typeInput: ElementRef<HTMLInputElement>;
    buttonDisplayValue: string;
    filterForm: UntypedFormGroup;
    readonly allStatuses: JobStatus[];
    readonly allTypes: JobType[];
    readonly jobStatusTranslations: Map<JobStatus, string>;
    readonly jobTypeTranslations: Map<JobType, string>;
    readonly allowedEntityTypes: EntityType[];
    selectedTypes: JobType[];
    typeFilterInput: string;
    typeInputFocused: boolean;
    private jobFilter;
    private propagateChange;
    constructor(fb: UntypedFormBuilder, translate: TranslateService, cd: ChangeDetectorRef);
    ngOnInit(): void;
    get filteredTypes(): JobType[];
    get typeInputPlaceholder(): string;
    addType(event: MatAutocompleteSelectedEvent): void;
    removeType(type: JobType): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(filter?: JobFilter): void;
    hasActiveFilters(): boolean;
    resetFilters(): void;
    closeFilterMenu(): void;
    applyFilters(): void;
    private updateButtonDisplayValue;
    static ɵfac: i0.ɵɵFactoryDeclaration<TaskManagerFilterComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TaskManagerFilterComponent, "tb-task-manager-filter", never, {}, {}, never, never, false, never>;
}
