import { OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { NestedTreeControl } from '@angular/cdk/tree';
import { MatTreeNestedDataSource } from '@angular/material/tree';
import { DatePipe } from '@angular/common';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { HttpClient } from '@angular/common/http';
import { AppState } from '@core/core.state';
import { EntityGroupService } from '@core/http/entity-group.service';
import { TenantService } from '@core/http/tenant.service';
import { CustomerService } from '@core/http/customer.service';
import { EntityGroup, EntityGroupType } from '@shared/models/entity-group.model';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { EntityGroupTableConfigService } from '@home/services/entity-group-table-config.service';
import * as i0 from "@angular/core";
export type TenantHierarchyNodeType = 'tenantGroup' | 'tenant' | 'groupCategory' | 'entityGroup' | 'customer';
export interface TenantHierarchyNode {
    id: string;
    type: TenantHierarchyNodeType;
    name: string;
    icon: string;
    children: TenantHierarchyNode[];
    loaded: boolean;
    loading: boolean;
    entityGroup?: EntityGroup;
    tenantId?: string;
    groupType?: EntityGroupType;
    customerId?: string;
    parentCustomerId?: string;
}
export declare class TenantHierarchyComponent implements OnInit, OnDestroy {
    private entityGroupService;
    private tenantService;
    private customerService;
    private translate;
    private datePipe;
    private dialog;
    private http;
    private store;
    private cd;
    private groupTableService;
    private destroy$;
    treeControl: NestedTreeControl<TenantHierarchyNode, TenantHierarchyNode>;
    dataSource: MatTreeNestedDataSource<TenantHierarchyNode>;
    loading: boolean;
    selectedNode: TenantHierarchyNode;
    hierarchyGroupsConfig: EntityTableConfig<any>;
    treePanelVisible: boolean;
    constructor(entityGroupService: EntityGroupService, tenantService: TenantService, customerService: CustomerService, translate: TranslateService, datePipe: DatePipe, dialog: MatDialog, http: HttpClient, store: Store<AppState>, cd: ChangeDetectorRef, groupTableService: EntityGroupTableConfigService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    hasChild: (_: number, node: TenantHierarchyNode) => boolean;
    toggleNode(node: TenantHierarchyNode): void;
    toggleTreePanel(): void;
    onNodeSelect(node: TenantHierarchyNode): void;
    navigateUp(): void;
    private loadTenantGroups;
    private loadChildren;
    private loadTenantGroupMembers;
    private loadTenantCategories;
    private loadEntityGroups;
    private loadCustomerCategories;
    private loadCustomerEntityGroupMembers;
    private buildDefaultTenantGroupsTable;
    private buildGroupsTableConfig;
    private buildMembersTableConfig;
    private buildTenantGroupMembersTableConfig;
    private refreshTree;
    private findParentNode;
    static ɵfac: i0.ɵɵFactoryDeclaration<TenantHierarchyComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TenantHierarchyComponent, "tb-tenant-hierarchy", never, {}, {}, never, never, false, never>;
}
