import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { PageComponent } from '@shared/components/page.component';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup } from '@angular/forms';
import { AdminService } from '@core/http/admin.service';
import { HasConfirmForm } from '@core/guards/confirm-on-exit.guard';
import { MatDialog } from '@angular/material/dialog';
import { NotificationService } from '@core/http/notification.service';
import { HttpClient } from '@angular/common/http';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare class SmsProviderComponent extends PageComponent implements HasConfirmForm {
    protected store: Store<AppState>;
    private router;
    private adminService;
    private notificationService;
    private dialog;
    private http;
    private translate;
    fb: FormBuilder;
    smsProvider: FormGroup;
    private adminSettings;
    notificationSettingsForm: FormGroup;
    private notificationSettings;
    telegramForm: FormGroup;
    telegramTokenEdited: boolean;
    whatsappForm: FormGroup;
    private readonly authUser;
    constructor(store: Store<AppState>, router: Router, adminService: AdminService, notificationService: NotificationService, dialog: MatDialog, http: HttpClient, translate: TranslateService, fb: FormBuilder);
    private buildSmsProviderForm;
    sendTestSms(): void;
    save(): void;
    confirmForm(): FormGroup;
    private buildGeneralServerSettingsForm;
    saveNotification(): void;
    isSysAdmin(): boolean;
    private buildTelegramForm;
    private loadTelegram;
    private applyTelegramConfig;
    saveTelegram(): void;
    sendTestTelegram(): void;
    discardTelegram(): void;
    private notify;
    private buildWhatsAppForm;
    private loadWhatsApp;
    private applyWhatsAppConfig;
    saveWhatsApp(): void;
    sendTestWhatsApp(): void;
    discardWhatsApp(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SmsProviderComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SmsProviderComponent, "tb-sms-provider", never, {}, {}, never, never, false, never>;
}
