import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CustomerService } from '@core/http/customer.service';
import { TenantService } from '@core/http/tenant.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { Dashboard, DashboardInfo, DashboardSetup } from '@app/shared/models/dashboard.models';
import { DashboardService } from '@app/core/http/dashboard.service';
import { ImportExportService } from '@shared/import-export/import-export.service';
import { EdgeService } from '@core/http/edge.service';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class DashboardsTableConfigResolver {
    private store;
    private dashboardService;
    private customerService;
    private tenantService;
    private edgeService;
    private dialogService;
    private homeDialogs;
    private importExport;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private entityGroupService;
    private permissionService;
    private readonly config;
    constructor(store: Store<AppState>, dashboardService: DashboardService, customerService: CustomerService, tenantService: TenantService, edgeService: EdgeService, dialogService: DialogService, homeDialogs: HomeDialogsService, importExport: ImportExportService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, entityGroupService: EntityGroupService, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<DashboardInfo | Dashboard>>;
    configureColumns(dashboardScope: string, includeCustomers?: boolean): Array<any>;
    configureEntityFunctions(dashboardScope: string): void;
    configureCellActions(dashboardScope: string): Array<CellActionDescriptor<DashboardInfo>>;
    configureGroupActions(dashboardScope: string): Array<GroupActionDescriptor<DashboardInfo>>;
    configureAddActions(dashboardScope: string): Array<HeaderActionDescriptor>;
    openDashboard($event: Event, dashboard: DashboardInfo): void;
    importDashboard(_$event: Event): void;
    private editMissingAliases;
    exportDashboard($event: Event, dashboard: DashboardInfo): void;
    dashboardWizard($event: Event): void;
    dashboardWizardForCustomer($event: Event): void;
    manageOwnerAndGroups($event: Event, dashboard: DashboardInfo): void;
    onDashboardAction(action: EntityAction<DashboardInfo>): boolean;
    addDashboardsToEdge($event: Event): void;
    unassignFromEdge($event: Event, dashboard: DashboardInfo): void;
    unassignDashboardsFromEdge($event: Event, dashboards: Array<DashboardInfo>): void;
    saveAndAssignDashboard(dashboard: DashboardSetup): Observable<Dashboard>;
    static ɵfac: i0.ɵɵFactoryDeclaration<DashboardsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<DashboardsTableConfigResolver>;
}
