import { ActivatedRouteSnapshot } from '@angular/router';
import { CellActionDescriptor, EntityTableColumn, EntityTableConfig, GroupActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { MatDialog } from '@angular/material/dialog';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ReportService } from '@core/http/report.service';
import { DialogService } from '@core/services/dialog.service';
import { Report } from '@home/pages/reporting/models/report.models';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class ReportsTableConfigResolver {
    private store;
    private reportService;
    private dialogService;
    private translate;
    private datePipe;
    private dialog;
    private permissionService;
    private readonly config;
    constructor(store: Store<AppState>, reportService: ReportService, dialogService: DialogService, translate: TranslateService, datePipe: DatePipe, dialog: MatDialog, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<Report>>;
    configureColumns(): Array<EntityTableColumn<Report>>;
    private getFormatLabel;
    private getStatusLabel;
    configureEntityFunctions(): void;
    configureCellActions(): Array<CellActionDescriptor<Report>>;
    private isViewableFormat;
    downloadReport($event: Event, report: Report): void;
    private fetchAndSave;
    onReportAction(action: EntityAction<Report>): boolean;
    viewReport($event: Event, report: Report): void;
    makePublic($event: Event, report: Report): void;
    makePrivate($event: Event, report: Report): void;
    configureGroupActions(): Array<GroupActionDescriptor<Report>>;
    exportSelectedReports($event: Event, reports: Report[]): void;
    splitViewReports($event: Event, reports: Report[]): void;
    configureAddActions(): Array<any>;
    generateReport(): Observable<Report>;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<ReportsTableConfigResolver>;
}
