import { ChangeDetectorRef, ElementRef, QueryList } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { AbstractControl, UntypedFormBuilder, UntypedFormGroup, ValidationErrors } from '@angular/forms';
import { Role, RoleType } from '@shared/models/role.model';
import { EntityComponent } from '../../components/entity/entity.component';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import * as i0 from "@angular/core";
interface PermissionRow {
    resource: string;
    operations: string[];
    resourceFilter: string;
    operationFilter: string;
}
export declare class RoleComponent extends EntityComponent<Role> {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: Role;
    protected entitiesTableConfigValue: EntityTableConfig<Role>;
    protected fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    roleTypes: RoleType[];
    roleTypeTranslations: Map<RoleType, string>;
    rbacResources: string[];
    rbacResourceTranslations: Map<string, string>;
    rbacOperationTranslations: Map<string, string>;
    readonly separatorKeyCodes: readonly [13, 188];
    permissionRows: PermissionRow[];
    restrictionRows: PermissionRow[];
    groupOperations: string[];
    groupOperationFilter: string;
    operationInputs: QueryList<ElementRef<HTMLInputElement>>;
    restrictionOperationInputs: QueryList<ElementRef<HTMLInputElement>>;
    groupOperationInput: ElementRef<HTMLInputElement>;
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: Role, entitiesTableConfigValue: EntityTableConfig<Role>, fb: UntypedFormBuilder, cd: ChangeDetectorRef);
    hideDelete(): boolean;
    onRoleIdCopied(): void;
    isSystemRole(): boolean;
    isGenericRole(): boolean;
    buildForm(entity: Role): UntypedFormGroup;
    updateForm(entity: Role): void;
    onRoleTypeChanged(newType: RoleType): void;
    addPermissionRow(): void;
    removePermissionRow(index: number): void;
    clearResource(index: number): void;
    onResourceSelected(event: MatAutocompleteSelectedEvent, index: number): void;
    filteredResources(index: number): string[];
    getResourceDisplayName(resource: string): string;
    getRelevantOperations(resource: string): string[];
    filteredOperationsForRow(index: number): string[];
    addOperationToRow(event: MatAutocompleteSelectedEvent, index: number): void;
    removeOperationFromRow(index: number, op: string): void;
    getOperationLabel(op: string): string;
    addRestrictionRow(): void;
    removeRestrictionRow(index: number): void;
    clearRestrictionResource(index: number): void;
    onRestrictionResourceSelected(event: MatAutocompleteSelectedEvent, index: number): void;
    filteredRestrictionResources(index: number): string[];
    filteredRestrictionOperationsForRow(index: number): string[];
    addRestrictionOperationToRow(event: MatAutocompleteSelectedEvent, index: number): void;
    removeRestrictionOperationFromRow(index: number, op: string): void;
    restoreRestrictionResourceFilter(index: number): void;
    filteredGroupOperations(): string[];
    addGroupOperation(event: MatAutocompleteSelectedEvent): void;
    removeGroupOperation(op: string): void;
    restoreResourceFilter(index: number): void;
    private loadRestrictions;
    private loadPermissions;
    permissionsNotEmpty(control: AbstractControl): ValidationErrors | null;
    private syncPermissionsToForm;
    private syncRestrictionsToForm;
    private buildRestrictionsObject;
    private buildPermissionsObject;
    static ɵfac: i0.ɵɵFactoryDeclaration<RoleComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RoleComponent, "tb-role", never, {}, {}, never, never, false, never>;
}
export {};
