import { ChangeDetectorRef, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatAutocompleteTrigger, MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormControl, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityGroup, EntityGroupType } from '@shared/models/entity-group.model';
import { EntityGroupService } from '@core/http/entity-group.service';
import { DeviceService } from '@core/http/device.service';
import { AssetService } from '@core/http/asset.service';
import { EntityViewService } from '@core/http/entity-view.service';
import { EdgeService } from '@core/http/edge.service';
import { DashboardService } from '@core/http/dashboard.service';
import { CustomerService } from '@core/http/customer.service';
import { UserService } from '@core/http/user.service';
import { PermissionService } from '@core/services/permission.service';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export interface ManageOwnerGroupsDialogData {
    entityId: string;
    entityType: EntityType;
    entityGroupType: EntityGroupType;
    currentCustomerId: string;
    currentGroups: EntityGroup[];
    targetTenantId?: string;
}
interface OwnerOption {
    id: string;
    name: string;
    isTenant: boolean;
}
export declare class ManageOwnerGroupsDialogComponent extends DialogComponent<ManageOwnerGroupsDialogComponent, boolean> implements OnInit, OnDestroy {
    protected store: Store<AppState>;
    protected router: Router;
    data: ManageOwnerGroupsDialogData;
    dialogRef: MatDialogRef<ManageOwnerGroupsDialogComponent, boolean>;
    private fb;
    private cdr;
    private matDialog;
    private translate;
    private deviceService;
    private assetService;
    private entityViewService;
    private edgeService;
    private dashboardService;
    private customerService;
    private userService;
    private entityGroupService;
    private permissionService;
    groupInput: ElementRef<HTMLInputElement>;
    autoTrigger: MatAutocompleteTrigger;
    form: UntypedFormGroup;
    entityType: typeof EntityType;
    selectedGroups: EntityGroup[];
    groupSearchCtrl: FormControl<string>;
    ownerSearchCtrl: FormControl<any>;
    filteredOwners: OwnerOption[];
    selectedOwner: OwnerOption;
    tenantOption: OwnerOption;
    filteredGroups: EntityGroup[];
    groupsLoaded: boolean;
    isSaving: boolean;
    searchTextForCreate: string;
    private destroy$;
    private searchSub;
    private ownerSearchSub;
    private reopenPanel;
    private allOwnerOptions;
    constructor(store: Store<AppState>, router: Router, data: ManageOwnerGroupsDialogData, dialogRef: MatDialogRef<ManageOwnerGroupsDialogComponent, boolean>, fb: UntypedFormBuilder, cdr: ChangeDetectorRef, matDialog: MatDialog, translate: TranslateService, deviceService: DeviceService, assetService: AssetService, entityViewService: EntityViewService, edgeService: EdgeService, dashboardService: DashboardService, customerService: CustomerService, userService: UserService, entityGroupService: EntityGroupService, permissionService: PermissionService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    displayOwnerFn: (owner: OwnerOption) => string;
    onOwnerSelected(event: MatAutocompleteSelectedEvent): void;
    clearOwner(): void;
    trackGroupById(_index: number, group: EntityGroup): string;
    private doSearch;
    addGroup(event: MatAutocompleteSelectedEvent): void;
    removeGroup(group: EntityGroup): void;
    createNewGroup(): void;
    cancel(): void;
    confirm(): void;
    private getChangeOwnerTask;
    private getRemoveOwnerTask;
    static ɵfac: i0.ɵɵFactoryDeclaration<ManageOwnerGroupsDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ManageOwnerGroupsDialogComponent, "tb-manage-owner-groups-dialog", never, {}, {}, never, never, false, never>;
}
export {};
