import { GridsterComponent, GridsterConfig, GridsterItem, GridsterItemComponentInterface } from 'angular-gridster2';
import { Widget, WidgetPosition } from '@app/shared/models/widget.models';
import { WidgetLayout, WidgetLayouts } from '@app/shared/models/dashboard.models';
import { IDashboardWidget, WidgetAction, WidgetContext, WidgetHeaderAction } from './widget-component.models';
import { Timewindow } from '@shared/models/time/time.models';
import { Observable, Subject } from 'rxjs';
import { IterableDiffer, KeyValueDiffer } from '@angular/core';
import { IAliasController, IStateController } from '@app/core/api/widget-api.models';
import { UtilsService } from '@core/services/utils.service';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { TbContextMenuEvent } from '@shared/models/jquery-event.models';
export interface WidgetsData {
    widgets: Array<Widget>;
    widgetLayouts?: WidgetLayouts;
}
export interface ContextMenuItem {
    enabled: boolean;
    shortcut?: string;
    icon: string;
    value: string;
    iconRow?: boolean;
    iconGrid?: boolean;
}
export interface DashboardContextMenuItem extends ContextMenuItem {
    action: (contextMenuEvent: TbContextMenuEvent) => void;
}
export interface WidgetContextMenuItem extends ContextMenuItem {
    action: (contextMenuEvent: TbContextMenuEvent, widget: Widget) => void;
    subItems?: WidgetContextMenuItem[];
}
export interface DashboardCallbacks {
    onEditWidget?: ($event: Event, widget: Widget) => void;
    onCopyWidget?: ($event: Event, widget: Widget) => void;
    replaceReferenceWithWidgetCopy?: ($event: Event, widget: Widget) => void;
    onExportWidget?: ($event: Event, widget: Widget, widgeTitle: string) => void;
    onRemoveWidget?: ($event: Event, widget: Widget) => void;
    onWidgetMouseDown?: ($event: Event, widget: Widget) => void;
    onDashboardMouseDown?: ($event: Event) => void;
    onWidgetClicked?: ($event: Event, widget: Widget) => void;
    prepareDashboardContextMenu?: ($event: Event) => Array<DashboardContextMenuItem>;
    prepareWidgetContextMenu?: ($event: Event, widget: Widget, isReference: boolean) => Array<WidgetContextMenuItem>;
    onWidgetChangeStart?: () => void;
    onWidgetChangeEnd?: () => void;
}
export type WidgetSelectionMode = 'replace' | 'toggle';
export interface IDashboardComponent {
    utils: UtilsService;
    gridsterOpts: GridsterConfig;
    gridster: GridsterComponent;
    dashboardWidgets: DashboardWidgets;
    mobileAutofillHeight: boolean;
    isMobileSize: boolean;
    isEdit: boolean;
    hiddenLayers?: Set<number>;
    lockedLayers?: Set<number>;
    autofillHeight: boolean;
    dashboardTimewindow: Timewindow;
    dashboardTimewindowChanged: Observable<Timewindow>;
    aliasController: IAliasController;
    stateController: IStateController;
    onUpdateTimewindow(startTimeMs: number, endTimeMs: number, interval?: number, persist?: boolean): void;
    onResetTimewindow(): void;
    resetHighlight(): void;
    highlightWidget(widgetId: string, delay?: number): any;
    focusWidgetForEdit(widgetId: string, drawerLeftX?: number, verticalOnly?: boolean): void;
    selectWidget(widgetId: string, delay?: number, mode?: WidgetSelectionMode): any;
    getSelectedWidget(): Widget;
    getSelectedWidgets(): Widget[];
    selectAllWidgets(): void;
    captureZoomBeforeEdit(): void;
    cycleStackedSelection(direction?: 1 | -1): boolean;
    getEventGridPosition(event: TbContextMenuEvent | KeyboardEvent): WidgetPosition;
    notifyGridsterOptionsChanged(): any;
    pauseChangeNotifications(): any;
    resumeChangeNotifications(): any;
    notifyLayoutUpdated(): any;
    /** Chunked initial mount: called per admission step so the (OnPush) dashboard
     *  re-evaluates its widget ngFor. Optional — see DashboardWidgets.doCheck. */
    notifyWidgetsAdmitted?(): void;
    /** State keep-alive: grid-geometry fingerprint. A hidden state generation is
     *  only restorable while this matches — its widgets' coordinates are
     *  expressed in these units. */
    stateSwapCacheKey?(): string;
    keepHiddenWidgets?(widgets: Array<DashboardWidget>): Array<DashboardWidget>;
    zoomScale: number;
    zoomPercent: number;
    minZoom: number;
    maxZoom: number;
    zoomIn(): void;
    zoomOut(): void;
    zoomReset(): void;
    zoomFit(): void;
}
export declare const maxGridsterCol = 3000;
export declare const maxGridsterRow = 3000;
export declare class DashboardWidgets implements Iterable<DashboardWidget> {
    private dashboard;
    private widgetsDiffer;
    private widgetLayoutsDiffer;
    highlightedMode: boolean;
    readonly selectionChange$: Subject<void>;
    dashboardWidgets: Array<DashboardWidget>;
    widgets: Iterable<Widget>;
    widgetLayouts: WidgetLayouts;
    parentDashboard?: IDashboardComponent;
    popoverComponent?: TbPopoverComponent;
    [Symbol.iterator](): Iterator<DashboardWidget>;
    private admittedCount;
    private admissionRafId;
    private revision;
    private static readonly MAX_HIDDEN_GENERATIONS;
    private static readonly NO_WIDGETS;
    private shownStateKey;
    private hiddenGenerations;
    private hiddenWidgetsCache;
    get stateHiddenWidgets(): Array<DashboardWidget>;
    dropHiddenGeneration(): void;
    private activeCache;
    private activeCacheKey;
    get activeDashboardWidgets(): Array<DashboardWidget>;
    constructor(dashboard: IDashboardComponent, widgetsDiffer: IterableDiffer<Widget>, widgetLayoutsDiffer: KeyValueDiffer<string, WidgetLayout>);
    private startChunkedAdmission;
    doCheck(): void;
    private applyUpdateRecord;
    widgetLayoutsUpdated(): void;
    setWidgets(widgets: Iterable<Widget>, widgetLayouts: WidgetLayouts): void;
    highlightWidget(widgetId: string): DashboardWidget;
    selectWidget(widgetId: string, mode?: WidgetSelectionMode): DashboardWidget;
    resetHighlight(): DashboardWidget;
    isHighlighted(widget: DashboardWidget): boolean;
    isNotHighlighted(widget: DashboardWidget): boolean;
    getSelectedWidget(): DashboardWidget;
    getSelectedWidgets(): DashboardWidget[];
    clearSelection(): void;
    selectAll(): void;
    notifySelectionChanged(): void;
    private findWidgetById;
    updateRowsAndSort(): void;
    sortWidgets(): void;
}
export declare class DashboardWidget implements GridsterItem, IDashboardWidget {
    private dashboard;
    widget: Widget;
    private widgetLayoutValue?;
    private parentDashboard?;
    private popoverComponent?;
    private highlightedValue;
    private selectedValue;
    private selectedCallback;
    resizableHandles: any;
    private resizableFromLayout;
    isFullscreen: boolean;
    isReference: boolean;
    stateHidden: boolean;
    color: string;
    backgroundColor: string;
    padding: string;
    margin: string;
    borderRadius: string;
    border: string;
    title$: Observable<string>;
    titleTooltip: string;
    showTitle: boolean;
    titleStyle: ComponentStyle;
    titleIcon: string;
    showTitleIcon: boolean;
    titleIconStyle: ComponentStyle;
    dropShadow: boolean;
    enableFullscreen: boolean;
    enableDataExport: boolean;
    hasTimewindow: boolean;
    hasAggregation: boolean;
    onlyQuickInterval: boolean;
    onlyHistoryTimewindow: boolean;
    style: ComponentStyle;
    showWidgetTitlePanel: boolean;
    showWidgetActions: boolean;
    customHeaderActions: Array<WidgetHeaderAction>;
    widgetActions: Array<WidgetAction>;
    widgetContext: WidgetContext;
    widgetId: string;
    private gridsterItemComponentSubject;
    private gridsterItemComponentValue;
    private aspectRatio;
    private heightValue;
    private widthValue;
    private rowsValue;
    private colsValue;
    get mobileHide(): boolean;
    get desktopHide(): boolean;
    set gridsterItemComponent(item: GridsterItemComponentInterface);
    get gridsterItemComponent(): GridsterItemComponentInterface;
    get itemElement(): HTMLElement | undefined;
    private preserveAspectRatioApplied;
    private applyPreserveAspectRatio;
    get highlighted(): boolean;
    set highlighted(highlighted: boolean);
    onSelected(selectedCallback: (selected: boolean) => void): void;
    get selected(): boolean;
    set selected(selected: boolean);
    get widgetLayout(): WidgetLayout;
    set widgetLayout(value: WidgetLayout);
    private _widgetLayoutUpdated;
    constructor(dashboard: IDashboardComponent, widget: Widget, widgetLayoutValue?: WidgetLayout, parentDashboard?: IDashboardComponent, popoverComponent?: TbPopoverComponent);
    applyThemeAwareColors(): void;
    gridsterItemComponent$(): Observable<GridsterItemComponentInterface>;
    updateWidgetParams(detectChanges?: boolean): void;
    updateParamsFromData(detectChanges?: boolean): void;
    private updateCustomHeaderActions;
    private filterCustomHeaderAction;
    get x(): number;
    set x(_: number);
    get y(): number;
    set y(_: number);
    get preserveAspectRatio(): boolean;
    get cols(): number;
    set cols(cols: number);
    get rows(): number;
    set rows(rows: number);
    get sizeX(): number;
    set sizeX(sizeX: number);
    get sizeY(): number;
    set sizeY(sizeY: number);
    get layerIndex(): number;
    set layerIndex(_: number);
    get layer(): number;
    get zOrder(): number;
    get layerHidden(): boolean;
    get layerLocked(): boolean;
    get runtimeHidden(): boolean;
    computeRuntimeHidden(isEdit: boolean): boolean;
    get dragEnabled(): boolean;
    get resizeEnabled(): boolean;
    get widgetOrder(): number;
    updatePosition(x: number, y: number): void;
}
