import { ElementRef, OnInit } from '@angular/core';
import { MatFormFieldAppearance, SubscriptSizing } from '@angular/material/form-field';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { EntityGroup, EntityGroupType } from '@shared/models/entity-group.model';
import { EntityGroupService } from '@core/http/entity-group.service';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare const ALL_ENTITY_GROUP_ID = "ALL";
export declare class EntityGroupAutocompleteComponent implements ControlValueAccessor, OnInit {
    private entityGroupService;
    private fb;
    private translate;
    selectGroupFormGroup: UntypedFormGroup;
    private modelValue;
    private groupTypeValue;
    private customerIdValue;
    filteredGroups: Observable<EntityGroup[]>;
    searchText: string;
    private dirty;
    private refresh$;
    private propagateChange;
    set groupType(groupType: EntityGroupType);
    set customerId(customerId: string);
    labelText: string;
    appearance: MatFormFieldAppearance;
    required: boolean;
    disabled: boolean;
    showAllOption: boolean;
    subscriptSizing: SubscriptSizing;
    groupInput: ElementRef;
    constructor(entityGroupService: EntityGroupService, fb: UntypedFormBuilder, translate: TranslateService);
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    ngOnInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string | null): void;
    onFocus(): void;
    private reset;
    private updateView;
    displayGroupFn(group?: EntityGroup): string | undefined;
    private fetchGroups;
    private createAllGroup;
    textIsNotEmpty(text: string): boolean;
    clear(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityGroupAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityGroupAutocompleteComponent, "tb-entity-group-autocomplete", never, { "groupType": { "alias": "groupType"; "required": false; }; "customerId": { "alias": "customerId"; "required": false; }; "labelText": { "alias": "labelText"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "showAllOption": { "alias": "showAllOption"; "required": false; }; "subscriptSizing": { "alias": "subscriptSizing"; "required": false; }; }, {}, never, never, false, never>;
}
