import { ElementRef, OnDestroy, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormControl, FormGroup } from '@angular/forms';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { MatButton } from '@angular/material/button';
import { Store } from '@ngrx/store';
import { TranslateService } from '@ngx-translate/core';
import { AppState } from '@core/core.state';
import { EntityType } from '@shared/models/entity-type.models';
import { NotificationType } from '@shared/models/notification.models';
import { ReportService } from '@core/http/report.service';
import { RecipeService } from '@core/http/recipe.service';
import { Recipe, RecipeData } from '@shared/models/recipe.models';
import { SchedulerEvent, SchedulerEventType, RepeatType, ReportTemplate, TimerUnit, TriggerOperator, TriggerCompareMode, TargetType } from '@home/pages/reporting/models/report.models';
import { EntityGroupType } from '@shared/models/entity-group.model';
import { DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { DatasourceType } from '@shared/models/widget.models';
import { Observable } from 'rxjs';
import { EntityAlias, EntityAliases } from '@shared/models/alias.models';
import { EntityAliasSelectCallbacks } from '@home/components/widget/lib/settings/common/alias/entity-alias-select.component.models';
import { IAliasController } from '@core/api/widget-api.models';
import { CustomerService } from '@core/http/customer.service';
import { Customer } from '@shared/models/customer.model';
import * as i0 from "@angular/core";
export interface SchedulerEventDialogData {
    event: SchedulerEvent;
    isEdit: boolean;
}
export declare class SchedulerEventDialogComponent implements OnInit, OnDestroy {
    private dialogRef;
    data: SchedulerEventDialogData;
    private fb;
    private store;
    private dialog;
    private reportService;
    private recipeService;
    private customerService;
    private translate;
    eventForm: FormGroup;
    isEdit: boolean;
    isSubmitting: boolean;
    repeatExpanded: boolean;
    triggerExpanded: boolean;
    schedulerEventTypes: SchedulerEventType[];
    SchedulerEventType: typeof SchedulerEventType;
    selectedEventType: SchedulerEventType;
    TargetType: typeof TargetType;
    TargetTypeTranslationMap: {
        GENERATE_REPORT?: {
            type: TargetType;
            label: string;
        }[];
        UPDATE_ATTRIBUTES?: {
            type: TargetType;
            label: string;
        }[];
        SEND_RPC_REQUEST?: {
            type: TargetType;
            label: string;
        }[];
        UPDATE_FIRMWARE?: {
            type: TargetType;
            label: string;
        }[];
        SEND_RECIPE_DATA?: {
            type: TargetType;
            label: string;
        }[];
        CUSTOM?: {
            type: TargetType;
            label: string;
        }[];
    };
    selectedTargetType: TargetType;
    entityTypeUser: EntityType;
    entityTypeCustomer: EntityType;
    entityTypeNotificationTarget: EntityType;
    entityTypeDevice: EntityType;
    entityTypeAsset: EntityType;
    allowedEntityTypes: EntityType[];
    rpcAllowedEntityTypes: EntityType[];
    schedulerTargetEntityTypes: {
        type: EntityType | string;
        label: string;
        disabled: boolean;
    }[];
    schedulerTargetGroupTypes: {
        type: EntityGroupType | string;
        label: string;
        disabled: boolean;
    }[];
    rpcGroupTypes: {
        type: EntityGroupType | string;
        label: string;
        disabled: boolean;
    }[];
    entityTypeDeviceProfile: EntityType;
    triggerOperators: TriggerOperator[];
    TriggerOperatorSymbols: {
        EQUALS: string;
        NOT_EQUALS: string;
        GREATER: string;
        LESS: string;
        GREATER_OR_EQUAL: string;
        LESS_OR_EQUAL: string;
    };
    triggerCompareModes: TriggerCompareMode[];
    TriggerCompareMode: typeof TriggerCompareMode;
    datasourceType: typeof DatasourceType;
    dataKeyType: typeof DataKeyType;
    triggerDatasourceTypes: DatasourceType[];
    entityAliases: EntityAliases;
    entityAliasSelectCallbacks: EntityAliasSelectCallbacks;
    aliasController: IAliasController;
    availableEntityTypes: EntityType[];
    notificationType: typeof NotificationType;
    notificationTypes: NotificationType[];
    repeatTypes: (RepeatType.DAILY | RepeatType.EVERY_N_DAYS | RepeatType.WEEKLY | RepeatType.EVERY_N_WEEKS | RepeatType.MONTHLY | RepeatType.YEARLY | RepeatType.TIMER_BASED)[];
    templates: ReportTemplate[];
    filteredTemplates: ReportTemplate[];
    templateSearchControl: FormControl<string | ReportTemplate>;
    private selectedTemplateId;
    daysOfWeek: {
        value: number;
        label: string;
    }[];
    timerUnits: TimerUnit[];
    ownerInput: ElementRef<HTMLInputElement>;
    currentUserEmail: string;
    ownerSearchControl: FormControl<string | Customer>;
    filteredOwners: Observable<Customer[]>;
    selectedOwner: Customer | null;
    private _templateFilterWired;
    private destroy$;
    constructor(dialogRef: MatDialogRef<SchedulerEventDialogComponent>, data: SchedulerEventDialogData, fb: FormBuilder, store: Store<AppState>, dialog: MatDialog, reportService: ReportService, recipeService: RecipeService, customerService: CustomerService, translate: TranslateService);
    ngOnDestroy(): void;
    recipesForDevice: Recipe[];
    recipeDataRecords: RecipeData[];
    ngOnInit(): void;
    private initRecipeCascadeWatchers;
    private preloadRecipeCascadeState;
    private initAliasController;
    private loadTemplates;
    private filterTemplates;
    private initOwnerAutocomplete;
    private fetchCustomers;
    displayOwnerFn: (value: Customer | string) => string;
    clearOwnerSelection(event: Event): void;
    private buildForm;
    get triggerConditions(): FormArray;
    private buildConditionsFormArray;
    private createConditionFormGroup;
    addCondition(): void;
    removeCondition(index: number): void;
    private resetAllConditionKeys;
    get attributeRows(): FormArray;
    private buildAttributeRows;
    addAttributeRow(): void;
    removeAttributeRow(index: number): void;
    private clearAttributeKeys;
    private getEntityTypeFromId;
    getTargetEntityType(): EntityType;
    getTargetEntityLabel(): string;
    getTargetGroupType(): EntityGroupType;
    getOwnerEntityGroupType(): EntityGroupType;
    getTargetAllowedEntityTypes(): EntityType[];
    getTargetAllowedGroupTypes(): {
        type: EntityGroupType | string;
        label: string;
        disabled: boolean;
    }[];
    getTargetTabs(): {
        type: TargetType;
        label: string;
    }[];
    isNonReportType(): boolean;
    getTargetOriginatorId(): any;
    getAttributeScopeLabel(): string;
    isRepeatDisabled(): boolean;
    isTriggerDisabled(): boolean;
    getEventTypeLabel(type: SchedulerEventType): string;
    isReportType(): boolean;
    isCustomType(): boolean;
    isAttributesType(): boolean;
    isRpcType(): boolean;
    isFirmwareType(): boolean;
    isRecipeDataType(): boolean;
    isDeviceOnlyType(): boolean;
    onEventTypeChange(type: SchedulerEventType): void;
    onTargetTypeChange(value: TargetType): void;
    getRepeatTypeLabel(type: RepeatType): string;
    showRepeatInterval(): boolean;
    getRepeatIntervalLabel(): string;
    getRepeatIntervalErrorMessage(): string;
    showDaysOfWeek(): boolean;
    showTimerFields(): boolean;
    getTimerUnitLabel(unit: TimerUnit): string;
    getOperatorLabel(operator: TriggerOperator): string;
    getDatasourceTypeTranslation(type: DatasourceType): string;
    getTriggerDatasourceType(): DatasourceType;
    getTriggerEntityIdForDataKeys(): any;
    hasSameKeyError(): boolean;
    conditionHasSameKeyError(index: number): boolean;
    createEntityAlias(alias: string, allowedEntityTypes?: EntityType[]): Observable<EntityAlias>;
    editEntityAlias(entityAlias: EntityAlias, allowedEntityTypes?: EntityType[]): Observable<EntityAlias>;
    private buildTriggerConfig;
    save(): void;
    cancel(): void;
    displayTemplateFn: (template: ReportTemplate) => string;
    onTemplateSelected(event: MatAutocompleteSelectedEvent): void;
    onTemplateFocus(): void;
    clearTemplateSelection(event: Event): void;
    createTarget($event: Event, button: MatButton): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SchedulerEventDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SchedulerEventDialogComponent, "tb-scheduler-event-dialog", never, {}, {}, never, never, false, never>;
}
