import { ChangeDetectorRef, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '@home/components/entity/entity.component';
import { FormArray, FormControl, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { EntityType } from '@shared/models/entity-type.models';
import { NotificationType } from '@shared/models/notification.models';
import { ReportService } from '@core/http/report.service';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { SchedulerEvent, SchedulerEventType, ReportTemplate, RepeatType, TimerUnit, TriggerOperator, TriggerCompareMode, TargetType } from '@home/pages/reporting/models/report.models';
import { EntityGroupType } from '@shared/models/entity-group.model';
import { CustomerService } from '@core/http/customer.service';
import { Customer } from '@shared/models/customer.model';
import { DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { DatasourceType } from '@shared/models/widget.models';
import { IAliasController } from '@core/api/widget-api.models';
import { EntityAliasSelectCallbacks } from '@home/components/widget/lib/settings/common/alias/entity-alias-select.component.models';
import { MatDialog } from '@angular/material/dialog';
import { Observable } from 'rxjs';
import * as i0 from "@angular/core";
export declare class SchedulerEventComponent extends EntityComponent<SchedulerEvent> implements OnInit, OnDestroy {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: SchedulerEvent;
    protected entitiesTableConfigValue: EntityTableConfig<SchedulerEvent>;
    fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    private reportService;
    private dialog;
    private customerService;
    schedulerEventTypes: SchedulerEventType[];
    SchedulerEventType: typeof SchedulerEventType;
    selectedEventType: SchedulerEventType;
    entityTypeUser: EntityType;
    entityTypeNotificationTarget: EntityType;
    entityTypeDevice: EntityType;
    entityTypeAsset: EntityType;
    notificationType: typeof NotificationType;
    notificationTypes: NotificationType[];
    TargetType: typeof TargetType;
    selectedTargetType: TargetType;
    entityTypeCustomer: EntityType;
    entityTypeDeviceProfile: EntityType;
    allowedEntityTypes: EntityType[];
    rpcAllowedEntityTypes: EntityType[];
    schedulerTargetEntityTypes: {
        type: EntityType | string;
        label: string;
        disabled: boolean;
    }[];
    schedulerTargetGroupTypes: {
        type: EntityGroupType | string;
        label: string;
        disabled: boolean;
    }[];
    rpcGroupTypes: {
        type: EntityGroupType | string;
        label: string;
        disabled: boolean;
    }[];
    ownerInput: ElementRef<HTMLInputElement>;
    currentUserEmail: string;
    ownerSearchControl: FormControl<string | Customer>;
    filteredOwners: Observable<Customer[]>;
    selectedOwner: Customer | null;
    repeatTypes: (RepeatType.DAILY | RepeatType.EVERY_N_DAYS | RepeatType.WEEKLY | RepeatType.EVERY_N_WEEKS | RepeatType.MONTHLY | RepeatType.YEARLY | RepeatType.TIMER_BASED)[];
    templates: ReportTemplate[];
    filteredTemplates: ReportTemplate[];
    templateSearchControl: FormControl<string | ReportTemplate>;
    private selectedTemplateId;
    daysOfWeek: {
        value: number;
        label: string;
    }[];
    timerUnits: TimerUnit[];
    repeatExpanded: boolean;
    isTimerBased: boolean;
    triggerExpanded: boolean;
    triggerOperators: TriggerOperator[];
    TriggerCompareMode: typeof TriggerCompareMode;
    triggerDatasourceTypes: DatasourceType[];
    datasourceType: typeof DatasourceType;
    aliasController: IAliasController;
    entityAliasSelectCallbacks: EntityAliasSelectCallbacks;
    private entityAliases;
    private availableEntityTypes;
    private pendingUserId;
    private pendingTargetIds;
    private pendingTargetNames;
    private pendingNotificationTemplateId;
    private pendingNotificationTemplateName;
    dataKeyType: typeof DataKeyType;
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: SchedulerEvent, entitiesTableConfigValue: EntityTableConfig<SchedulerEvent>, fb: UntypedFormBuilder, cd: ChangeDetectorRef, reportService: ReportService, dialog: MatDialog, customerService: CustomerService);
    ngOnDestroy(): void;
    private initAliasController;
    private createEntityAlias;
    private editEntityAlias;
    private templatesLoaded;
    set isEdit(isEdit: boolean);
    get isEdit(): boolean;
    private populateEditModeFields;
    ngOnInit(): void;
    private setupRepeatTypeSubscription;
    private loadTemplates;
    private loadTemplatesIfNeeded;
    private filterTemplates;
    buildForm(entity: SchedulerEvent): UntypedFormGroup;
    updateForm(entity: SchedulerEvent): void;
    getRepeatTypeLabel(type: RepeatType): string;
    showRepeatInterval(): boolean;
    showTimerFields(): boolean;
    getTimerUnitLabel(unit: TimerUnit): string;
    getRepeatIntervalLabel(): string;
    showDaysOfWeek(): boolean;
    displayTemplateFn: (template: ReportTemplate) => string;
    onTemplateSelected(event: MatAutocompleteSelectedEvent): void;
    onTemplateFocus(): void;
    clearTemplateSelection(event: Event): void;
    hideDelete(): boolean;
    getEventTypeLabel(type: SchedulerEventType): string;
    isReportType(): boolean;
    isCustomType(): boolean;
    isAttributesType(): boolean;
    isRpcType(): boolean;
    isFirmwareType(): boolean;
    isNonReportType(): boolean;
    isDeviceOnlyType(): boolean;
    getTargetTabs(): {
        type: TargetType;
        label: string;
    }[];
    onTargetTypeChange(value: TargetType): void;
    getTargetEntityType(): EntityType;
    getTargetEntityLabel(): string;
    getTargetOriginatorId(): any;
    getTargetAllowedGroupTypes(): {
        type: EntityGroupType | string;
        label: string;
        disabled: boolean;
    }[];
    getTargetGroupType(): EntityGroupType;
    getOwnerEntityGroupType(): EntityGroupType;
    displayOwnerFn: (value: Customer | string) => string;
    clearOwnerSelection(event: Event): void;
    private initOwnerAutocomplete;
    private tenantOwnerOption;
    private fetchCustomers;
    onEventTypeChange(type: SchedulerEventType): void;
    prepareFormValue(formValue: any): any;
    onRepeatEnabledChange(): void;
    isRepeatDisabled(): boolean;
    isTriggerDisabled(): boolean;
    getRecipientsDisplay(): string;
    getNotificationTemplateDisplay(): string;
    get triggerConditions(): FormArray;
    private buildConditionsFormArray;
    private createConditionFormGroup;
    addCondition(): void;
    removeCondition(index: number): void;
    private resetAllConditionKeys;
    getOperatorLabel(op: TriggerOperator): string;
    getDatasourceTypeTranslation(dsType: DatasourceType): string;
    getTriggerDatasourceType(): DatasourceType;
    getTriggerEntityIdForDataKeys(): any;
    onTriggerEnabledChange(): void;
    onTriggerDatasourceTypeChange(): void;
    hasSameKeyError(): boolean;
    conditionHasSameKeyError(index: number): boolean;
    private buildTriggerConfig;
    private getEntityTypeFromId;
    get attributeRows(): FormArray;
    private buildAttributeRows;
    addAttributeRow(): void;
    removeAttributeRow(index: number): void;
    private clearAttributeKeys;
    exportEvent(): void;
    onSchedulerEventIdCopied($event: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SchedulerEventComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SchedulerEventComponent, "tb-scheduler-event", never, { "isEdit": { "alias": "isEdit"; "required": false; }; }, {}, never, never, false, never>;
}
