import { ActivatedRouteSnapshot } from '@angular/router';
import { CellActionDescriptor, EntityTableColumn, EntityLinkTableColumn, EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ReportService } from '@core/http/report.service';
import { DialogService } from '@core/services/dialog.service';
import { MatDialog } from '@angular/material/dialog';
import { SchedulerEvent } from '@home/pages/reporting/models/report.models';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class SchedulerEventsTableConfigResolver {
    private store;
    private reportService;
    private dialogService;
    private translate;
    private datePipe;
    private dialog;
    private permissionService;
    private readonly config;
    constructor(store: Store<AppState>, reportService: ReportService, dialogService: DialogService, translate: TranslateService, datePipe: DatePipe, dialog: MatDialog, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<SchedulerEvent>>;
    private disabledCellStyle;
    configureColumns(): Array<EntityTableColumn<SchedulerEvent> | EntityLinkTableColumn<SchedulerEvent>>;
    private getScheduleLabel;
    private getTimerUnitLabel;
    configureEntityFunctions(): void;
    configureCellActions(): Array<CellActionDescriptor<SchedulerEvent>>;
    configureAddActions(): Array<any>;
    addEvent(): Observable<SchedulerEvent>;
    editEvent($event: Event, event: SchedulerEvent): void;
    toggleEnabled($event: Event, event: SchedulerEvent): void;
    onEventAction(action: EntityAction<SchedulerEvent>): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<SchedulerEventsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<SchedulerEventsTableConfigResolver>;
}
