import { OnInit, AfterViewInit, ElementRef } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { MatMenuTrigger } from '@angular/material/menu';
import { SelectionModel } from '@angular/cdk/collections';
import { MatDialog } from '@angular/material/dialog';
import { TranslateService } from '@ngx-translate/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ReportService } from '@core/http/report.service';
import { DialogService } from '@core/services/dialog.service';
import { SchedulerEvent } from '@home/pages/reporting/models/report.models';
import * as i0 from "@angular/core";
export declare class SchedulerEventsTableComponent implements OnInit, AfterViewInit {
    private store;
    private reportService;
    private dialog;
    private dialogService;
    private translate;
    displayedColumns: string[];
    dataSource: MatTableDataSource<SchedulerEvent, MatPaginator>;
    selection: SelectionModel<SchedulerEvent>;
    isLoading: boolean;
    dataLoading: boolean;
    totalElements: number;
    pageSize: number;
    pageIndex: number;
    textSearch: string;
    textSearchMode: boolean;
    currentUserId: string;
    displayPagination: boolean;
    filterReportTemplate: string;
    filterUser: string;
    appliedFilterReportTemplate: string;
    appliedFilterUser: string;
    reportTemplates: Array<{
        id: string;
        name: string;
    }>;
    users: Array<{
        id: string;
        name: string;
    }>;
    paginator: MatPaginator;
    sort: MatSort;
    searchInputField: ElementRef;
    filterMenuTrigger: MatMenuTrigger;
    constructor(store: Store<AppState>, reportService: ReportService, dialog: MatDialog, dialogService: DialogService, translate: TranslateService);
    ngOnInit(): void;
    loadFilterOptions(): void;
    ngAfterViewInit(): void;
    loadData(): void;
    onPageChange(event: any): void;
    onSearch(searchText: string): void;
    private searchDebounceTimer;
    onSearchChange(value: string): void;
    enterFilterMode(): void;
    exitFilterMode(): void;
    addEvent(): void;
    editEvent(event: SchedulerEvent): void;
    toggleEnabled(event: SchedulerEvent): void;
    deleteEvent(event: SchedulerEvent): void;
    getEventTypeLabel(event: SchedulerEvent): string;
    getRepeatTypeLabel(event: SchedulerEvent): string;
    getScheduleLabel(event: SchedulerEvent): string;
    formatDate(timestamp: number): string;
    isAllSelected(): boolean;
    masterToggle(): void;
    hasActiveFilters(): boolean;
    onFilterChange(): void;
    resetFilters(): void;
    closeFilterMenu(): void;
    applyFilters(): void;
    exportSelected(): void;
    deleteSelected(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SchedulerEventsTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SchedulerEventsTableComponent, "tb-scheduler-events-table", never, {}, {}, never, never, false, never>;
}
