import { ActivatedRoute, ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityColumn, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Device, DeviceInfo, DeviceInfoQuery } from '@app/shared/models/device.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { DeviceService } from '@app/core/http/device.service';
import { CustomerService } from '@core/http/customer.service';
import { TenantService } from '@core/http/tenant.service';
import { BroadcastService } from '@core/services/broadcast.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import { EdgeService } from '@core/http/edge.service';
import { PageLink } from '@shared/models/page/page-link';
import { EntityGroupService } from '@core/http/entity-group.service';
import { EntityId } from '@shared/models/id/entity-id';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class DevicesTableConfigResolver {
    private store;
    private broadcast;
    private deviceService;
    private customerService;
    private tenantService;
    private dialogService;
    private edgeService;
    private homeDialogs;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private entityGroupService;
    private permissionService;
    private readonly config;
    private customerId;
    constructor(store: Store<AppState>, broadcast: BroadcastService, deviceService: DeviceService, customerService: CustomerService, tenantService: TenantService, dialogService: DialogService, edgeService: EdgeService, homeDialogs: HomeDialogsService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, entityGroupService: EntityGroupService, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<DeviceInfo>>;
    onLoadAction(route: ActivatedRoute): void;
    configureColumns(deviceScope: string, includeCustomers?: boolean): Array<EntityColumn<DeviceInfo>>;
    private deviceState;
    private deviceStateStyle;
    configureEntityFunctions(deviceScope: string): void;
    prepareDeviceInfoQuery(pageLink: PageLink): DeviceInfoQuery;
    configureCellActions(deviceScope: string): Array<CellActionDescriptor<DeviceInfo>>;
    configureGroupActions(deviceScope: string): Array<GroupActionDescriptor<DeviceInfo>>;
    configureAddActions(deviceScope: string): Array<HeaderActionDescriptor>;
    private openDevice;
    importDevices($event: Event): void;
    deviceWizard($event: Event): void;
    deviceWizardForCustomer($event: Event): void;
    manageCredentials($event: Event, device: Device): void;
    onDeviceAction(action: EntityAction<DeviceInfo>, config: EntityTableConfig<DeviceInfo>): boolean;
    manageOwnerAndGroups($event: Event, device: DeviceInfo): void;
    addDevicesToEdge($event: Event): void;
    unassignFromEdge($event: Event, device: DeviceInfo): void;
    unassignDevicesFromEdge($event: Event, devices: Array<DeviceInfo>): void;
    checkConnectivity($event: Event, deviceId: EntityId, afterAdd?: boolean): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DevicesTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<DevicesTableConfigResolver>;
}
