import { OnInit, AfterViewInit, ElementRef, OnDestroy } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { MatMenuTrigger } from '@angular/material/menu';
import { SelectionModel } from '@angular/cdk/collections';
import { MatDialog } from '@angular/material/dialog';
import { DatePipe } from '@angular/common';
import { TranslateService } from '@ngx-translate/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ReportService } from '@core/http/report.service';
import { DialogService } from '@core/services/dialog.service';
import { BaseData, HasId } from '@shared/models/base-data';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { CalendarOptions, EventInput, EventClickArg, DatesSetArg } from '@fullcalendar/core';
import { FullCalendarComponent } from '@fullcalendar/angular';
import { DateClickArg } from '@fullcalendar/interaction';
import { SchedulerEvent } from '@home/pages/reporting/models/report.models';
import { CalendarViewType } from './scheduler.models';
import * as i0 from "@angular/core";
export declare class SchedulerPageComponent implements OnInit, AfterViewInit, OnDestroy {
    private elementRef;
    private store;
    private reportService;
    private dialog;
    private dialogService;
    private translate;
    private datePipe;
    viewMode: CalendarViewType;
    displayedColumns: string[];
    dataSource: MatTableDataSource<SchedulerEvent, MatPaginator>;
    selection: SelectionModel<SchedulerEvent>;
    isLoading: boolean;
    totalElements: number;
    pageSize: number;
    pageIndex: number;
    textSearch: string;
    textSearchMode: boolean;
    currentUserId: string;
    currentAuthority: string;
    filterEventType: string;
    filterUser: string;
    filterEnabled: string;
    appliedFilterEventType: string;
    appliedFilterUser: string;
    appliedFilterEnabled: string;
    schedulerEventTypes: Array<{
        value: string;
        label: string;
    }>;
    filterUsers: Array<{
        id: string;
        name: string;
    }>;
    isDetailsOpen: boolean;
    selectedEntityId: HasId;
    detailsConfig: EntityTableConfig<SchedulerEvent>;
    allEvents: SchedulerEvent[];
    calendarEvents: EventInput[];
    calendarOptions: CalendarOptions;
    showDatePicker: boolean;
    pickerYear: number;
    pickerMonth: number;
    pickerPosition: {
        top: number;
        left: number;
    };
    pickerArrowLeft: string;
    readonly months: string[];
    showTooltip: boolean;
    tooltipAnimated: boolean;
    tooltipEvent: SchedulerEvent | null;
    tooltipPosition: {
        top: number;
        left: number;
    };
    tooltipAbove: boolean;
    private tooltipShowTimer;
    private tooltipHideTimer;
    paginator: MatPaginator;
    sort: MatSort;
    searchInputField: ElementRef;
    calendarComponent: FullCalendarComponent;
    filterMenuTrigger: MatMenuTrigger;
    private searchDebounceTimer;
    private currentCalendarStart;
    private currentCalendarEnd;
    titleOverlayStyle: {
        top: number;
        left: number;
        width: number;
        height: number;
    } | null;
    constructor(elementRef: ElementRef, store: Store<AppState>, reportService: ReportService, dialog: MatDialog, dialogService: DialogService, translate: TranslateService, datePipe: DatePipe);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private updateTitleOverlay;
    private attachRipples;
    private initCalendarSlidingPill;
    private updateTodayHighlight;
    onEscapeKey(): void;
    setViewMode(mode: CalendarViewType): void;
    loadDataSilent(): void;
    loadData(): void;
    private loadTableData;
    private loadAllEvents;
    private updateCalendarEvents;
    onDatesSet(arg: DatesSetArg): void;
    onEventClick(arg: EventClickArg): void;
    onDateClick(arg: DateClickArg): void;
    onTitleHover(hovered: boolean): void;
    onTitleClick(): void;
    closeDatePicker(): void;
    applyDatePicker(): void;
    changeYear(delta: number): void;
    changeMonth(delta: number): void;
    onYearWheel(event: WheelEvent): void;
    onMonthWheel(event: WheelEvent): void;
    onEventMouseEnter(info: any): void;
    onEventMouseLeave(): void;
    onPageChange(event: any): void;
    onSearchChange(value: string): void;
    enterFilterMode(): void;
    exitFilterMode(): void;
    addEvent(): void;
    addEventOnDate(date: Date): void;
    downloadEvent(event: SchedulerEvent, $event: Event): void;
    importEvent(): void;
    editEvent(event: SchedulerEvent): void;
    onDetailsClose(): void;
    onEntityUpdated(entity: BaseData<HasId>): void;
    onEntityAction(action: EntityAction<SchedulerEvent>): boolean;
    toggleEnabled(event: SchedulerEvent): void;
    deleteSelected(): void;
    deleteEvent(event: SchedulerEvent): void;
    hasActiveFilters(): boolean;
    onFilterChange(): void;
    resetFilters(): void;
    closeFilterMenu(): void;
    applyFilters(): void;
    private updateFilterUsers;
    isAllSelected(): boolean;
    masterToggle(): void;
    getEventTypeLabel(event: SchedulerEvent): string;
    getScheduleLabel(event: SchedulerEvent): string;
    formatDate(timestamp: number): string;
    getTooltipDetails(event: SchedulerEvent): {
        label: string;
        value: string;
    }[];
    getEventTypeColorClass(event: SchedulerEvent): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<SchedulerPageComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SchedulerPageComponent, "tb-scheduler-page", never, {}, {}, never, never, false, never>;
}
