import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CustomerService } from '@core/http/customer.service';
import { TenantService } from '@core/http/tenant.service';
import { BroadcastService } from '@core/services/broadcast.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { EntityViewInfo } from '@app/shared/models/entity-view.models';
import { EntityViewService } from '@core/http/entity-view.service';
import { EdgeService } from '@core/http/edge.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class EntityViewsTableConfigResolver {
    private store;
    private broadcast;
    private entityViewService;
    private customerService;
    private tenantService;
    private edgeService;
    private dialogService;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private entityGroupService;
    private permissionService;
    private readonly config;
    private customerId;
    constructor(store: Store<AppState>, broadcast: BroadcastService, entityViewService: EntityViewService, customerService: CustomerService, tenantService: TenantService, edgeService: EdgeService, dialogService: DialogService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, entityGroupService: EntityGroupService, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<EntityViewInfo>>;
    configureColumns(entityViewScope: string, includeCustomers?: boolean): Array<any>;
    configureEntityFunctions(entityViewScope: string): void;
    configureCellActions(entityViewScope: string): Array<CellActionDescriptor<EntityViewInfo>>;
    configureGroupActions(entityViewScope: string): Array<GroupActionDescriptor<EntityViewInfo>>;
    configureAddActions(entityViewScope: string): Array<HeaderActionDescriptor>;
    entityViewWizard($event: Event): void;
    entityViewWizardForCustomer($event: Event): void;
    private openEntityView;
    manageOwnerAndGroups($event: Event, entityView: EntityViewInfo): void;
    onEntityViewAction(action: EntityAction<EntityViewInfo>, config: EntityTableConfig<EntityViewInfo>): boolean;
    addEntityViewsToEdge($event: Event): void;
    unassignFromEdge($event: Event, entityView: EntityViewInfo): void;
    unassignEntityViewsFromEdge($event: Event, entityViews: Array<EntityViewInfo>): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityViewsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<EntityViewsTableConfigResolver>;
}
