import { ElementRef, OnInit } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { RoleService } from '@core/http/role.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { CustomerService } from '@core/http/customer.service';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { Role, RoleType } from '@shared/models/role.model';
import { EntityGroup, EntityGroupType } from '@shared/models/entity-group.model';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export interface AddGroupPermissionDialogData {
    mode: 'roles' | 'permissions';
    entityGroupId: string;
}
export interface OwnerOption {
    id: string;
    name: string;
    type: string;
}
export declare class AddGroupPermissionDialogComponent extends DialogComponent<AddGroupPermissionDialogComponent> implements OnInit {
    protected store: Store<AppState>;
    protected router: Router;
    private roleService;
    private entityGroupService;
    private customerService;
    private translate;
    private fb;
    data: AddGroupPermissionDialogData;
    dialogRef: MatDialogRef<AddGroupPermissionDialogComponent>;
    form: UntypedFormGroup;
    mode: 'roles' | 'permissions';
    entityGroupId: string;
    loading: boolean;
    roleTypes: RoleType[];
    roleTypeTranslations: Map<RoleType, string>;
    allRoles: Role[];
    filteredRoles: Role[];
    userGroups: EntityGroup[];
    filteredUserGroups: EntityGroup[];
    entityGroups: EntityGroup[];
    filteredEntityGroups: EntityGroup[];
    entityGroupTypes: EntityGroupType[];
    entityGroupTypeTranslations: Map<EntityGroupType, string>;
    entityGroupOwners: OwnerOption[];
    filteredEntityGroupOwners: OwnerOption[];
    userGroupOwners: OwnerOption[];
    filteredUserGroupOwners: OwnerOption[];
    roleInput: ElementRef<HTMLInputElement>;
    entityGroupOwnerInput: ElementRef<HTMLInputElement>;
    entityGroupInput: ElementRef<HTMLInputElement>;
    userGroupOwnerInput: ElementRef<HTMLInputElement>;
    userGroupInput: ElementRef<HTMLInputElement>;
    constructor(store: Store<AppState>, router: Router, roleService: RoleService, entityGroupService: EntityGroupService, customerService: CustomerService, translate: TranslateService, fb: UntypedFormBuilder, data: AddGroupPermissionDialogData, dialogRef: MatDialogRef<AddGroupPermissionDialogComponent>);
    ngOnInit(): void;
    onRoleTypeChanged(): void;
    loadRoles(): void;
    private applyRoleTypeFilter;
    filterRoles(value: string): void;
    displayRole: (roleId: string) => string;
    isGroupRole(): boolean;
    loadAllEntityGroups(): void;
    loadEntityGroupsByType(): void;
    private buildEntityGroupOwnerOptions;
    filterEntityGroupOwners(value: string): void;
    displayEntityGroupOwner: (ownerId: string) => string;
    onEntityGroupOwnerSelected(ownerId: string): void;
    onEntityGroupTypeChanged(): void;
    private applyEntityGroupOwnerFilter;
    filterEntityGroups(value: string): void;
    displayEntityGroup: (groupId: string) => string;
    loadUserGroups(): void;
    private buildUserGroupOwnerOptions;
    filterUserGroupOwners(value: string): void;
    displayUserGroupOwner: (ownerId: string) => string;
    onUserGroupOwnerSelected(ownerId: string): void;
    filterUserGroups(value: string): void;
    displayUserGroup: (groupId: string) => string;
    private prefillOwner;
    save(): void;
    cancel(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AddGroupPermissionDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AddGroupPermissionDialogComponent, "tb-add-group-permission-dialog", never, {}, {}, never, never, false, never>;
}
