import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { RoleService } from '@core/http/role.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { CustomerService } from '@core/http/customer.service';
import { GroupPermission } from '@shared/models/role.model';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { SelectionModel } from '@angular/cdk/collections';
import * as i0 from "@angular/core";
export interface GroupPermissionRow {
    permission: GroupPermission;
    roleName: string;
    roleType: string;
    userGroupName?: string;
    userGroupOwner?: string;
    entityGroupName?: string;
    entityGroupType?: string;
    groupOwner?: string;
    /** True when the role is owned by a parent (e.g. tenant role viewed by customer user) */
    readOnly?: boolean;
}
export declare class GroupPermissionTableComponent extends PageComponent implements OnInit, OnDestroy, AfterViewInit {
    protected store: Store<AppState>;
    private roleService;
    private entityGroupService;
    private customerService;
    translate: TranslateService;
    dialog: MatDialog;
    private dialogService;
    private cd;
    displayedColumns: string[];
    dataSource: MatTableDataSource<GroupPermissionRow, MatPaginator>;
    selection: SelectionModel<GroupPermissionRow>;
    loading: boolean;
    searchMode: boolean;
    searchText: string;
    sort: MatSort;
    paginator: MatPaginator;
    private activeValue;
    private dirtyValue;
    private entityGroupIdValue;
    private modeValue;
    private destroy$;
    set active(active: boolean);
    set entityGroupId(entityGroupId: string);
    set mode(mode: 'roles' | 'permissions');
    get mode(): 'roles' | 'permissions';
    get title(): string;
    constructor(store: Store<AppState>, roleService: RoleService, entityGroupService: EntityGroupService, customerService: CustomerService, translate: TranslateService, dialog: MatDialog, dialogService: DialogService, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    isAllSelected(): boolean;
    masterToggle(): void;
    toggleSearch(): void;
    applyFilter(filterValue: string): void;
    private updateColumns;
    loadData(): void;
    private enrichPermissions;
    addPermission(): void;
    viewRole($event: Event, row: GroupPermissionRow): void;
    deletePermission($event: Event, row: GroupPermissionRow): void;
    deleteSelected(): void;
    refresh(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<GroupPermissionTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<GroupPermissionTableComponent, "tb-group-permission-table", never, { "active": { "alias": "active"; "required": false; }; "entityGroupId": { "alias": "entityGroupId"; "required": false; }; "mode": { "alias": "mode"; "required": false; }; }, {}, never, never, false, never>;
}
