import { ElementRef } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormBuilder, FormControl, FormGroup } from '@angular/forms';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { EntityGroupService } from '@core/http/entity-group.service';
import { EntityGroup, EntityGroupType } from '@shared/models/entity-group.model';
import { RoleService } from '@core/http/role.service';
import { Role } from '@shared/models/role.model';
import { EntityService } from '@core/http/entity.service';
import { BaseData } from '@shared/models/base-data';
import { EntityId } from '@shared/models/id/entity-id';
import { Observable } from 'rxjs';
import { MatStepper } from '@angular/material/stepper';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { StepperSelectionEvent } from '@angular/cdk/stepper';
import * as i0 from "@angular/core";
export interface CreateEntityGroupDialogData {
    groupType: EntityGroupType;
    prefillName?: string;
    ownerId?: string;
}
export declare class CreateEntityGroupDialogComponent extends DialogComponent<CreateEntityGroupDialogComponent, EntityGroup> {
    protected store: Store<AppState>;
    protected router: Router;
    dialogRef: MatDialogRef<CreateEntityGroupDialogComponent, EntityGroup>;
    data: CreateEntityGroupDialogData;
    private fb;
    private entityGroupService;
    private roleService;
    private entityService;
    stepper: MatStepper;
    roleInput: ElementRef<HTMLInputElement>;
    detailsFormGroup: FormGroup;
    shareFormGroup: FormGroup;
    selectedIndex: number;
    customerSearchControl: FormControl<string>;
    filteredCustomers$: Observable<Array<BaseData<EntityId>>>;
    private selectedCustomer;
    groupRoles: Role[];
    selectedRoles: Role[];
    roleSearchControl: FormControl<string>;
    filteredRoles: Role[];
    separatorKeyCodes: number[];
    customerUserGroups: EntityGroup[];
    constructor(store: Store<AppState>, router: Router, dialogRef: MatDialogRef<CreateEntityGroupDialogComponent, EntityGroup>, data: CreateEntityGroupDialogData, fb: FormBuilder, entityGroupService: EntityGroupService, roleService: RoleService, entityService: EntityService);
    onCustomerFocus(): void;
    displayCustomerFn: (value: any) => string;
    onCustomerSelected(event: MatAutocompleteSelectedEvent): void;
    clearCustomer(): void;
    onRoleFocus(): void;
    onRoleSelected(event: MatAutocompleteSelectedEvent): void;
    removeRole(role: Role): void;
    private clearRoleInput;
    changeStep(event: StepperSelectionEvent): void;
    previousStep(): void;
    nextStep(): void;
    cancel(): void;
    save(): void;
    private getSelectedRoleIds;
    private loadCustomerUserGroups;
    static ɵfac: i0.ɵɵFactoryDeclaration<CreateEntityGroupDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CreateEntityGroupDialogComponent, "tb-create-entity-group-dialog", never, {}, {}, never, never, false, never>;
}
