import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormBuilder, FormGroup } from '@angular/forms';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { EntityView } from '@shared/models/entity-view.models';
import { MatStepper, StepperOrientation } from '@angular/material/stepper';
import { EntityType } from '@shared/models/entity-type.models';
import { Observable } from 'rxjs';
import { EntityViewService } from '@core/http/entity-view.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { EntityGroup } from '@shared/models/entity-group.model';
import { StepperSelectionEvent } from '@angular/cdk/stepper';
import { BreakpointObserver } from '@angular/cdk/layout';
import { EntityId } from '@shared/models/id/entity-id';
import { AttributeScope, DataKeyType } from '@shared/models/telemetry/telemetry.models';
import * as i0 from "@angular/core";
export interface EntityViewWizardDialogData {
    prefilledGroup?: EntityGroup;
    defaultOwnerId?: string;
}
export declare class EntityViewWizardDialogComponent extends DialogComponent<EntityViewWizardDialogComponent, EntityView> {
    protected store: Store<AppState>;
    protected router: Router;
    dialogRef: MatDialogRef<EntityViewWizardDialogComponent, EntityView>;
    private data;
    private entityViewService;
    private entityGroupService;
    private breakpointObserver;
    private fb;
    addEntityViewWizardStepper: MatStepper;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    selectedIndex: number;
    showNext: boolean;
    entityType: typeof EntityType;
    dataKeyType: typeof DataKeyType;
    attributeScope: typeof AttributeScope;
    allowedEntityTypes: EntityType[];
    entityViewDetailsFormGroup: FormGroup;
    ownerAndGroupsFormGroup: FormGroup;
    prefilledGroup: EntityGroup;
    defaultOwnerId: string;
    selectedEntityId: Observable<EntityId | null>;
    maxStartTimeMs: Observable<number | null>;
    minEndTimeMs: Observable<number | null>;
    constructor(store: Store<AppState>, router: Router, dialogRef: MatDialogRef<EntityViewWizardDialogComponent, EntityView>, data: EntityViewWizardDialogData, entityViewService: EntityViewService, entityGroupService: EntityGroupService, breakpointObserver: BreakpointObserver, fb: FormBuilder);
    cancel(): void;
    previousStep(): void;
    nextStep(): void;
    getFormLabel(index: number): string;
    get maxStepperIndex(): number;
    add(): void;
    private createEntityView;
    allValid(): boolean;
    changeStep($event: StepperSelectionEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityViewWizardDialogComponent, [null, null, null, { optional: true; }, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityViewWizardDialogComponent, "tb-entity-view-wizard", never, {}, {}, never, never, false, never>;
}
