import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormBuilder, FormGroup } from '@angular/forms';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { ActivationMethod, User } from '@shared/models/user.model';
import { MatStepper, StepperOrientation } from '@angular/material/stepper';
import { Observable } from 'rxjs';
import { UserService } from '@core/http/user.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { EntityGroup } from '@shared/models/entity-group.model';
import { StepperSelectionEvent } from '@angular/cdk/stepper';
import { BreakpointObserver } from '@angular/cdk/layout';
import { Authority } from '@shared/models/authority.enum';
import * as i0 from "@angular/core";
export interface UserWizardDialogData {
    tenantId: string;
    customerId: string;
    authority: Authority;
    prefilledGroup?: EntityGroup;
    defaultOwnerId?: string;
}
export declare class UserWizardDialogComponent extends DialogComponent<UserWizardDialogComponent, User> {
    protected store: Store<AppState>;
    protected router: Router;
    dialogRef: MatDialogRef<UserWizardDialogComponent, User>;
    private data;
    private userService;
    private entityGroupService;
    private breakpointObserver;
    private fb;
    private dialog;
    addUserWizardStepper: MatStepper;
    stepperOrientation: Observable<StepperOrientation>;
    stepperLabelPosition: Observable<'bottom' | 'end'>;
    selectedIndex: number;
    showNext: boolean;
    userDetailsFormGroup: FormGroup;
    ownerAndGroupsFormGroup: FormGroup;
    activationMethods: string[];
    activationMethodEnum: typeof ActivationMethod;
    activationMethodTranslations: Map<ActivationMethod, string>;
    activationMethod: ActivationMethod;
    prefilledGroup: EntityGroup;
    defaultOwnerId: string;
    targetTenantId: string;
    constructor(store: Store<AppState>, router: Router, dialogRef: MatDialogRef<UserWizardDialogComponent, User>, data: UserWizardDialogData, userService: UserService, entityGroupService: EntityGroupService, breakpointObserver: BreakpointObserver, fb: FormBuilder, dialog: MatDialog);
    cancel(): void;
    previousStep(): void;
    nextStep(): void;
    getFormLabel(index: number): string;
    get maxStepperIndex(): number;
    add(): void;
    private createUser;
    private displayActivationLink;
    allValid(): boolean;
    changeStep($event: StepperSelectionEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<UserWizardDialogComponent, [null, null, null, { optional: true; }, null, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<UserWizardDialogComponent, "tb-user-wizard", never, {}, {}, never, never, false, never>;
}
