import { ChangeDetectorRef, ElementRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '../../components/entity/entity.component';
import { FormControl, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { EntityType } from '@shared/models/entity-type.models';
import { TranslateService } from '@ngx-translate/core';
import { AssetInfo } from '@app/shared/models/asset.models';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { EntityGroupService } from '@core/http/entity-group.service';
import { EntityGroup } from '@shared/models/entity-group.model';
import { Observable } from 'rxjs';
import { CustomerService } from '@core/http/customer.service';
import { EntityService } from '@core/http/entity.service';
import { BaseData } from '@shared/models/base-data';
import { EntityId } from '@shared/models/id/entity-id';
import { MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { MatDialog } from '@angular/material/dialog';
import * as i0 from "@angular/core";
export declare class AssetComponent extends EntityComponent<AssetInfo> {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: AssetInfo;
    protected entitiesTableConfigValue: EntityTableConfig<AssetInfo>;
    fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    private entityGroupService;
    private entityService;
    private customerService;
    private matDialog;
    groupInput: ElementRef<HTMLInputElement>;
    ownerInput: ElementRef<HTMLInputElement>;
    entityType: typeof EntityType;
    assetScope: 'tenant' | 'customer' | 'customer_user' | 'edge';
    currentGroups: EntityGroup[];
    ownerDisplayValue: string;
    ownerSearchControl: FormControl<string>;
    filteredCustomers$: Observable<Array<BaseData<EntityId>>>;
    ownerSelected: boolean;
    private selectedCustomer;
    private currentGroupsOwnerId;
    selectedGroups: EntityGroup[];
    groupSearchControl: FormControl<string>;
    filteredGroups: EntityGroup[];
    groupSearchText: string;
    separatorKeyCodes: number[];
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: AssetInfo, entitiesTableConfigValue: EntityTableConfig<AssetInfo>, fb: UntypedFormBuilder, cd: ChangeDetectorRef, entityGroupService: EntityGroupService, entityService: EntityService, customerService: CustomerService, matDialog: MatDialog);
    ngOnInit(): void;
    private initOwnerAndGroups;
    hideDelete(): boolean;
    isAssignedToCustomer(entity: AssetInfo): boolean;
    displayOwnerFn: (value: any) => string;
    onOwnerFocus(): void;
    onOwnerSelected(event: MatAutocompleteSelectedEvent): void;
    clearOwner(): void;
    onGroupFocus(): void;
    removeGroup(group: EntityGroup): void;
    onGroupSelected(event: MatAutocompleteSelectedEvent): void;
    createNewGroup($event?: MouseEvent): void;
    private clearGroupInput;
    private updateGroupIds;
    buildForm(entity: AssetInfo): UntypedFormGroup;
    updateForm(entity: AssetInfo): void;
    onAssetIdCopied($event: any): void;
    onAssetProfileUpdated(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AssetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AssetComponent, "tb-asset", never, {}, {}, never, never, false, never>;
}
