import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CustomerService } from '@core/http/customer.service';
import { TenantService } from '@core/http/tenant.service';
import { BroadcastService } from '@core/services/broadcast.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { AssetInfo } from '@app/shared/models/asset.models';
import { AssetService } from '@app/core/http/asset.service';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import { EdgeService } from '@core/http/edge.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class AssetsTableConfigResolver {
    private store;
    private broadcast;
    private assetService;
    private customerService;
    private tenantService;
    private edgeService;
    private dialogService;
    private homeDialogs;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private entityGroupService;
    private permissionService;
    private readonly config;
    private customerId;
    constructor(store: Store<AppState>, broadcast: BroadcastService, assetService: AssetService, customerService: CustomerService, tenantService: TenantService, edgeService: EdgeService, dialogService: DialogService, homeDialogs: HomeDialogsService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, entityGroupService: EntityGroupService, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<AssetInfo>>;
    configureColumns(assetScope: string, includeCustomers?: boolean): Array<any>;
    configureEntityFunctions(assetScope: string): void;
    configureCellActions(assetScope: string): Array<CellActionDescriptor<AssetInfo>>;
    configureGroupActions(assetScope: string): Array<GroupActionDescriptor<AssetInfo>>;
    configureAddActions(assetScope: string): Array<HeaderActionDescriptor>;
    importAssets($event: Event): void;
    private openAsset;
    manageOwnerAndGroups($event: Event, asset: AssetInfo): void;
    onAssetAction(action: EntityAction<AssetInfo>, config: EntityTableConfig<AssetInfo>): boolean;
    addAssetsToEdge($event: Event): void;
    unassignFromEdge($event: Event, asset: AssetInfo): void;
    unassignAssetsFromEdge($event: Event, assets: Array<AssetInfo>): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AssetsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AssetsTableConfigResolver>;
}
