import { AfterViewInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { Router } from '@angular/router';
import { MatDialogRef } from '@angular/material/dialog';
import { MatStepper, StepperOrientation } from '@angular/material/stepper';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { BreakpointObserver } from '@angular/cdk/layout';
import { Observable } from 'rxjs';
import { DialogComponent } from '@shared/components/dialog.component';
import { EntityType } from '@shared/models/entity-type.models';
import { Integration, IntegrationType } from '@shared/models/integration.models';
import { Converter, ConverterType } from '@shared/models/converter.models';
import { TranslateService } from '@ngx-translate/core';
import { IntegrationService } from '@core/http/integration.service';
import { ConverterService } from '@core/http/converter.service';
import * as i0 from "@angular/core";
export declare class AddIntegrationDialogComponent extends DialogComponent<AddIntegrationDialogComponent, Integration> implements AfterViewInit {
    protected store: Store<AppState>;
    protected router: Router;
    data: any;
    dialogRef: MatDialogRef<AddIntegrationDialogComponent, Integration>;
    private fb;
    private translate;
    private breakpointObserver;
    private integrationService;
    private converterService;
    stepper: MatStepper;
    selectedIndex: number;
    entityTypes: typeof EntityType;
    stepperOrientation: Observable<StepperOrientation>;
    basicFormGroup: UntypedFormGroup;
    converterFormGroup: UntypedFormGroup;
    downlinkFormGroup: UntypedFormGroup;
    connectionFormGroup: UntypedFormGroup;
    integrationTypeInfoMap: Map<IntegrationType, import("@shared/models/integration.models").IntegrationTypeInfo>;
    uplinkConverters: Converter[];
    converterType: typeof ConverterType;
    private lastAutoName;
    get integrationType(): IntegrationType;
    get hideDownlink(): boolean;
    get isDownlinkSkipped(): boolean;
    get showCheckConnection(): boolean;
    constructor(store: Store<AppState>, router: Router, data: any, dialogRef: MatDialogRef<AddIntegrationDialogComponent, Integration>, fb: UntypedFormBuilder, translate: TranslateService, breakpointObserver: BreakpointObserver, integrationService: IntegrationService, converterService: ConverterService);
    ngAfterViewInit(): void;
    private onTypeChange;
    private updateConverterValidators;
    private loadConverters;
    get nextButtonLabel(): string;
    previousStep(): void;
    nextStep(): void;
    changeStep(index: number): void;
    checkConnection(): void;
    cancel(): void;
    add(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AddIntegrationDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AddIntegrationDialogComponent, "tb-add-integration-dialog", never, {}, {}, never, never, false, never>;
}
