import { OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { ConverterScriptLanguage, ConverterType } from '@shared/models/converter.models';
import { ScriptLanguage } from '@shared/models/rule-node.models';
import { NodeScriptTestService } from '@core/services/script/node-script-test.service';
import * as i0 from "@angular/core";
export declare const DEFAULT_JS_DECODER = "// Decode an uplink message from a buffer\n// payload - array of bytes\n// metadata - key/value object\n\n/** Decoder **/\n\n// decode payload to string\nvar payloadStr = decodeToString(payload);\n\n// decode payload to JSON\n// var data = decodeToJson(payload);\n\nreturn {\n  deviceName: metadata.deviceName || 'Device',\n  deviceType: 'default',\n  telemetry: { payload: payloadStr }\n};";
export declare const DEFAULT_RHAI_DECODER = "// decoder(payload, metadata) -> map\nlet payload_str = decodeToString(payload);\n#{\n  deviceName: metadata.deviceName ?? \"Device\",\n  deviceType: \"default\",\n  telemetry: #{ payload: payload_str }\n}";
export declare const DEFAULT_JS_ENCODER = "// encoder(msg, metadata, msgType) -> { contentType, data, metadata }\nreturn {\n  contentType: 'JSON',\n  data: JSON.stringify(msg),\n  metadata: {}\n};";
export declare const DEFAULT_RHAI_ENCODER = "// encoder(msg, metadata, msgType) -> map\n#{ contentType: \"JSON\", data: to_json(msg), metadata: #{} }";
export interface ConverterConfigValue {
    scriptLang?: ConverterScriptLanguage;
    decoder?: string;
    rhaiDecoder?: string;
    encoder?: string;
    rhaiEncoder?: string;
    entityType?: string;
    deviceName?: string;
    deviceProfile?: string;
    deviceLabel?: string;
    customerName?: string;
    deviceGroup?: string;
    telemetry?: string[];
    attributes?: string[];
    updateOnlyKeys?: string[];
}
export declare class ConverterConfigComponent implements ControlValueAccessor, OnInit, OnChanges, OnDestroy {
    private fb;
    private translate;
    private nodeScriptTestService;
    converterType: ConverterType;
    private showAdvancedValue;
    get showAdvanced(): boolean;
    set showAdvanced(value: boolean);
    scriptLanguage: typeof ScriptLanguage;
    readonly converterHelpers: string[];
    configForm: UntypedFormGroup;
    disabled: boolean;
    private destroy$;
    private propagateChange;
    private onTouched;
    constructor(fb: UntypedFormBuilder, translate: TranslateService, nodeScriptTestService: NodeScriptTestService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    get isUplink(): boolean;
    get isRhai(): boolean;
    get editorLanguage(): ScriptLanguage;
    get functionName(): string;
    get functionArgs(): string[];
    private activeControlName;
    private loadEditor;
    private saveEditor;
    private currentValue;
    testScript(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: ConverterConfigValue): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConverterConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConverterConfigComponent, "tb-converter-config", never, { "converterType": { "alias": "converterType"; "required": false; }; "showAdvanced": { "alias": "showAdvanced"; "required": false; }; }, {}, never, never, false, never>;
}
