import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { IntegrationType } from '@shared/models/integration.models';
import * as i0 from "@angular/core";
export declare class IntegrationTypeSelectComponent implements ControlValueAccessor, OnInit {
    translate: TranslateService;
    private fb;
    label: string;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    includeAll: boolean;
    typeInput: ElementRef;
    selectFormGroup: UntypedFormGroup;
    disabled: boolean;
    modelValue: IntegrationType | null;
    types: IntegrationType[];
    infoMap: Map<IntegrationType, import("@shared/models/integration.models").IntegrationTypeInfo>;
    filteredTypes: Observable<IntegrationType[]>;
    private dirty;
    private propagateChange;
    private onTouched;
    constructor(translate: TranslateService, fb: UntypedFormBuilder);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: IntegrationType | null): void;
    onFocus(): void;
    updateView(value: IntegrationType | string | null): void;
    displayTypeFn: (type?: IntegrationType | null) => string;
    private getSearchText;
    private fetchTypes;
    clear(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<IntegrationTypeSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<IntegrationTypeSelectComponent, "tb-integration-type-select", never, { "label": { "alias": "label"; "required": false; }; "required": { "alias": "required"; "required": false; }; "includeAll": { "alias": "includeAll"; "required": false; }; }, {}, never, never, false, never>;
}
