import { ElementRef, EventEmitter, Injector, NgZone, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { GridsterComponent } from 'angular-gridster2';
import { DashboardWidget } from '@home/models/dashboard-component.models';
import { ImageService } from '@core/http/image.service';
import { MatIconRegistry } from '@angular/material/icon';
import { RafService } from '@core/services/raf.service';
import { IAliasController, IStateController } from '@core/api/widget-api.models';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class ConsolidatedSymbolsComponent implements OnChanges, OnDestroy {
    private injector;
    private imageService;
    private iconRegistry;
    private raf;
    private imagePipe;
    private sanitizer;
    private ngZone;
    hostRef: ElementRef<HTMLElement>;
    members: DashboardWidget[];
    hiddenMembers: DashboardWidget[];
    gridster: GridsterComponent;
    aliasController: IAliasController;
    stateController: IStateController;
    gridsterMobileChanged: EventEmitter<void>;
    private lastGridsterMobile;
    private runtimes;
    private resizeObserver;
    private destroyed;
    private layoutReady;
    private layoutReadyResolve;
    private themeSubscription;
    private fontsReady;
    private readonly fontLoadingDoneHandler;
    private readonly pageVisibilityHandler;
    constructor(injector: Injector, imageService: ImageService, iconRegistry: MatIconRegistry, raf: RafService, imagePipe: ImagePipe, sanitizer: DomSanitizer, ngZone: NgZone);
    private rebuildScheduled;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    private ensureFontsReady;
    private recreateAllSymbols;
    private teardown;
    private rebuild;
    private layoutRetryToken;
    private layoutUntilStable;
    private settleTimer;
    private scheduleSettleCheck;
    private layoutMembers;
    private applyContainerStyle;
    private initMember;
    private showMemberError;
    private resolveTargetEntity;
    private buildMemberCtx;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConsolidatedSymbolsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConsolidatedSymbolsComponent, "tb-consolidated-symbols", never, { "members": { "alias": "members"; "required": false; }; "hiddenMembers": { "alias": "hiddenMembers"; "required": false; }; "gridster": { "alias": "gridster"; "required": false; }; "aliasController": { "alias": "aliasController"; "required": false; }; "stateController": { "alias": "stateController"; "required": false; }; }, { "gridsterMobileChanged": "gridsterMobileChanged"; }, never, never, true, never>;
}
