import { OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormArray, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { HasConfirmForm } from '@core/guards/confirm-on-exit.guard';
import { TranslateService } from '@ngx-translate/core';
import { ActivatedRoute } from '@angular/router';
import { NotificationDeliveryMethod } from '@shared/models/notification.models';
import { NotificationService } from '@core/http/notification.service';
import { DialogService } from '@core/services/dialog.service';
import { HttpClient } from '@angular/common/http';
import { MatDialog } from '@angular/material/dialog';
import * as i0 from "@angular/core";
interface LinkedDestination {
    channel: string;
    destinationDisplay: string;
    verifiedAt: number | null;
    createdTime: number;
}
interface TelegramLinkResponse {
    code: string;
    deeplink: string;
    botUsername: string;
    expiresAt: number;
}
type WhatsAppLinkStep = 'PHONE' | 'CODE';
export declare class NotificationSettingsComponent extends PageComponent implements OnInit, OnDestroy, HasConfirmForm {
    protected store: Store<AppState>;
    private route;
    private translate;
    private dialogService;
    private notificationService;
    private fb;
    private http;
    private dialog;
    notificationSettings: UntypedFormGroup;
    notificationDeliveryMethods: NotificationDeliveryMethod[];
    notificationDeliveryMethodInfoMap: Map<NotificationDeliveryMethod, import("@shared/models/notification.models").NotificationDeliveryMethodInfo>;
    destinations: LinkedDestination[];
    telegramLinkDialogTpl: TemplateRef<unknown>;
    linkActive: TelegramLinkResponse | null;
    private linkPollSub;
    private linkDialogRef;
    whatsappLinkDialogTpl: TemplateRef<unknown>;
    whatsappLinkStep: WhatsAppLinkStep;
    whatsappLinkForm: UntypedFormGroup | null;
    whatsappLinkExpiresAt: number | null;
    whatsappResendCooldownSec: number;
    whatsappBusy: boolean;
    private whatsappPollSub;
    private whatsappCooldownSub;
    private whatsappDialogRef;
    private deliveryMethods;
    constructor(store: Store<AppState>, route: ActivatedRoute, translate: TranslateService, dialogService: DialogService, notificationService: NotificationService, fb: UntypedFormBuilder, http: HttpClient, dialog: MatDialog);
    ngOnInit(): void;
    ngOnDestroy(): void;
    private buildNotificationSettingsForm;
    private patchNotificationSettings;
    private prepareNotificationSettings;
    resetSettings(): void;
    getChecked: (method?: NotificationDeliveryMethod) => boolean;
    getSomeChecked: () => any;
    getIndeterminate: (deliveryMethod?: NotificationDeliveryMethod) => boolean;
    changeInstanceTypeCheckBox: (value: boolean, deliveryMethod?: NotificationDeliveryMethod) => void;
    get notificationSettingsFormArray(): UntypedFormArray;
    save(): void;
    confirmForm(): UntypedFormGroup;
    loadDestinations(): void;
    hasDestination(channel: string): boolean;
    unlinkDestination(channel: string): void;
    startTelegramLink(): void;
    private startLinkPolling;
    private stopLinkPolling;
    copyToClipboard(value: string): void;
    startWhatsappLink(): void;
    sendWhatsappCode(): void;
    resendWhatsappCode(): void;
    verifyWhatsappCode(): void;
    cancelWhatsappLink(): void;
    private startWhatsappPolling;
    private stopWhatsappPolling;
    private startWhatsappCooldown;
    private stopWhatsappCooldown;
    private notify;
    static ɵfac: i0.ɵɵFactoryDeclaration<NotificationSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NotificationSettingsComponent, "tb-notification-settings", never, {}, {}, never, never, false, never>;
}
export {};
