import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, Injector, NgZone, OnDestroy, OnInit, Renderer2, ViewContainerRef } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ActivatedRoute, Router } from '@angular/router';
import { UtilsService } from '@core/services/utils.service';
import { Dashboard, DashboardConfiguration, LayoutType, WidgetLayout } from '@app/shared/models/dashboard.models';
import { DashboardContext, DashboardPageLayoutContext, DashboardPageLayouts, DashboardPageScope, IDashboardController } from './dashboard-page.models';
import { BreakpointObserver } from '@angular/cdk/layout';
import { AuthUser } from '@shared/models/user.model';
import { Widget, WidgetInfo, WidgetPosition, widgetType } from '@shared/models/widget.models';
import { DialogService } from '@core/services/dialog.service';
import { EntityService } from '@core/http/entity.service';
import { DashboardUtilsService } from '@core/services/dashboard-utils.service';
import { DashboardService } from '@core/http/dashboard.service';
import { DashboardContextMenuItem, IDashboardComponent, WidgetContextMenuItem } from '../../models/dashboard-component.models';
import { WidgetComponentService } from '../../components/widget/widget-component.service';
import { ItemBufferService } from '@core/services/item-buffer.service';
import { MatDialog } from '@angular/material/dialog';
import { EditWidgetComponent } from '@home/components/dashboard-page/edit-widget.component';
import { TranslateService } from '@ngx-translate/core';
import { ImportExportService } from '@shared/import-export/import-export.service';
import { AuthState } from '@app/core/auth/auth.models';
import { Overlay } from '@angular/cdk/overlay';
import { DashboardWidgetSelectComponent } from '@home/components/dashboard-page/dashboard-widget-select.component';
import { MobileService } from '@core/services/mobile.service';
import { DashboardReuseService } from '@core/services/dashboard-reuse.service';
import { DashboardSelectComponent } from '@shared/components/dashboard-select.component';
import { IAliasController } from '@core/api/widget-api.models';
import { MatButton } from '@angular/material/button';
import { TbPopoverService } from '@shared/components/popover.service';
import { ILayoutController } from '@home/components/dashboard-page/layout/layout.models';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { HasDirtyFlag } from '@core/guards/confirm-on-exit.guard';
import { HttpClient } from '@angular/common/http';
import * as i0 from "@angular/core";
export declare class DashboardPageComponent extends PageComponent implements IDashboardController, HasDirtyFlag, OnInit, AfterViewInit, OnDestroy {
    protected store: Store<AppState>;
    private window;
    private document;
    private breakpointObserver;
    private route;
    private router;
    private utils;
    private dashboardUtils;
    private entityService;
    private dialogService;
    private widgetComponentService;
    private dashboardService;
    private itembuffer;
    private importExport;
    private mobileService;
    private dialog;
    translate: TranslateService;
    private popoverService;
    private renderer;
    private ngZone;
    private embeddedValue;
    private overlay;
    private viewContainerRef;
    private cd;
    elRef: ElementRef;
    private injector;
    private http;
    private dashboardReuseService;
    LayoutType: typeof LayoutType;
    private destroyed;
    private forcePristine;
    get isDirty(): boolean;
    set isDirty(value: boolean);
    private configDirty;
    get dashboardDirty(): boolean;
    onBeforeUnload(event: BeforeUnloadEvent): void;
    authState: AuthState;
    authUser: AuthUser;
    dashboardPageClass: string;
    embedded: boolean;
    currentState: string;
    private hideToolbarValue;
    set hideToolbar(hideToolbar: boolean);
    get hideToolbar(): boolean;
    get scadaZoomCtrl(): ILayoutController | null;
    syncStateWithQueryParam: boolean;
    dashboard: Dashboard;
    dashboardConfiguration: DashboardConfiguration;
    parentDashboard?: IDashboardComponent;
    popoverComponent?: TbPopoverComponent;
    parentAliasController?: IAliasController;
    dashboardContainer: ElementRef<HTMLElement>;
    dashboardSelect: DashboardSelectComponent;
    dashboardContent: ElementRef<HTMLElement>;
    saving: boolean;
    private static readonly SAVE_TIMEOUT_MS;
    prevDashboard: Dashboard;
    private undoStack;
    private redoStack;
    private pendingUndoSnapshot;
    private static readonly UNDO_DEPTH;
    iframeMode: boolean;
    widgetEditMode: boolean;
    singlePageMode: boolean;
    forceFullscreen: boolean;
    readonly: boolean;
    isMobileApp: boolean;
    private isFullscreenValue;
    get isFullscreen(): boolean;
    set isFullscreen(value: boolean);
    isEdit: boolean;
    isEditingWidget: boolean;
    isEditingWidgetClosed: boolean;
    isMobile: boolean;
    forceDashboardMobileMode: boolean;
    isAddingWidget: boolean;
    isAddingWidgetClosed: boolean;
    editDetailsShrink: boolean;
    filterWidgetTypes: widgetType[];
    activeLayer: number;
    hiddenLayers: Set<number>;
    lockedLayers: Set<number>;
    private lastPastePosition;
    private static readonly PASTE_CASCADE_OFFSET;
    private static readonly DEFAULT_LAYER_DEFINITIONS;
    isToolbarOpened: boolean;
    sentientVersion: string;
    isToolbarOpenedAnimate: boolean;
    isRightLayoutOpened: boolean;
    editingWidget: Widget;
    editingWidgetLayout: WidgetLayout;
    editingWidgetOriginal: Widget;
    editingWidgetLayoutOriginal: WidgetLayout;
    editingWidgetSubtitle: string;
    editingLayoutCtx: DashboardPageLayoutContext;
    thingsboardVersion: string;
    translatedDashboardTitle: string;
    currentDashboardId: string;
    currentCustomerId: string;
    currentDashboardScope: DashboardPageScope;
    setStateDashboardId: boolean;
    addingLayoutCtx: DashboardPageLayoutContext;
    mainLayoutSize: {
        width: string;
        height: string;
        maxWidth: string;
        minWidth: string;
    };
    rightLayoutSize: {
        width: string;
        height: string;
    };
    private dashboardLogoCache;
    private defaultDashboardLogo;
    private dashboardResize$;
    dashboardCtx: DashboardContext;
    layouts: DashboardPageLayouts;
    updateBreadcrumbs: EventEmitter<any>;
    private rxSubscriptions;
    get toolbarOpened(): boolean;
    set toolbarOpened(toolbarOpened: boolean);
    get rightLayoutOpened(): boolean;
    set rightLayoutOpened(rightLayoutOpened: boolean);
    get mobileDisplayRightLayoutFirst(): boolean;
    set mobileDisplayRightLayoutFirst(mobileDisplayRightLayoutFirst: boolean);
    editWidgetComponent: EditWidgetComponent;
    dashboardWidgetSelectComponent: DashboardWidgetSelectComponent;
    private changeMobileSize;
    constructor(store: Store<AppState>, window: Window, document: Document, breakpointObserver: BreakpointObserver, route: ActivatedRoute, router: Router, utils: UtilsService, dashboardUtils: DashboardUtilsService, entityService: EntityService, dialogService: DialogService, widgetComponentService: WidgetComponentService, dashboardService: DashboardService, itembuffer: ItemBufferService, importExport: ImportExportService, mobileService: MobileService, dialog: MatDialog, translate: TranslateService, popoverService: TbPopoverService, renderer: Renderer2, ngZone: NgZone, embeddedValue: any, overlay: Overlay, viewContainerRef: ViewContainerRef, cd: ChangeDetectorRef, elRef: ElementRef, injector: Injector, http: HttpClient, dashboardReuseService: DashboardReuseService);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    private prefetchWidgetTypes;
    private routeReattaching;
    private pristineConfiguration;
    tbOnRouteReattached(): void;
    private init;
    private updateDashboardCss;
    private cleanupDashboardCss;
    private reset;
    ngOnDestroy(): void;
    runChangeDetection(): void;
    openToolbar(): void;
    closeToolbar(): void;
    showCloseToolbar(): boolean;
    hideFullscreenButton(): boolean;
    toolbarAlwaysOpen(): boolean;
    private hideToolbarSetting;
    displayTitle(): boolean;
    private getTranslatedDashboardTitle;
    dashboardTitleColor(): string;
    dashboardTitleStyle(): {
        [key: string]: string;
    };
    onDashboardTitleChanged(): void;
    private isDefaultBlackTitleColor;
    displayExport(): boolean;
    displayUpdateDashboardImage(): boolean;
    displayDashboardTimewindow(): boolean;
    displayDashboardsSelect(): boolean;
    displayEntitiesSelect(): boolean;
    displayFilters(): boolean;
    showDashboardLogo(): boolean;
    get dashboardLogo(): string;
    showRightLayoutSwitch(): boolean;
    toggleLayouts(): void;
    openRightLayout(): void;
    updateLayoutSizes(): void;
    private updateMainLayoutSize;
    private updateRightLayoutSize;
    private calculateWidth;
    isPublicUser(): boolean;
    isTenantAdmin(): boolean;
    isSystemAdmin(): boolean;
    exportDashboard($event: Event): void;
    openEntityAliases($event: Event): void;
    openFilters($event: Event): void;
    openDashboardSettings($event: Event): void;
    manageDashboardStates($event: Event): void;
    isCurrentLayoutScada(): boolean;
    getActiveLayerName(): string;
    getCurrentLayerDefinitions(): {
        id: number;
        name?: string;
    }[];
    setActiveLayer(layer: number): void;
    isLayerHidden(layer: number): boolean;
    isLayerLocked(layer: number): boolean;
    toggleLayerHidden(layer: number): void;
    toggleLayerLocked(layer: number): void;
    private refreshLayerStateOnDashboards;
    getLayerWidgetCounts(): {
        [layerId: number]: number;
    };
    openLayerSettings(): void;
    manageDashboardLayouts($event: Event): void;
    private moveWidgets;
    private updateDashboardLayouts;
    private updateStates;
    importWidget($event: Event): void;
    private editMissingAliases;
    currentDashboardIdChanged(dashboardId: string): void;
    toggleDashboardEditMode(): void;
    saveDashboard(closeEditMode?: boolean): void;
    openDashboardState(state: string, openRightLayout?: boolean): void;
    private initRouteChrome;
    private updateLayouts;
    private updateLayout;
    private updateReuseCacheability;
    private mobileToggleLayoutFn;
    private registerMobileToggleLayout;
    private unregisterMobileToggleLayout;
    private announcePageVisibility;
    tbOnRouteDetached(): void;
    private setEditMode;
    private resetHighlight;
    private canCapture;
    private undoEnabled;
    canUndo(): boolean;
    canRedo(): boolean;
    private resetUndo;
    private pushSnapshot;
    pushUndoSnapshot(): void;
    beginWidgetChange(): void;
    commitWidgetChange(): void;
    undo(): void;
    redo(): void;
    private restoreDashboardSnapshot;
    private entityAliasesUpdated;
    private filtersUpdated;
    private notifyDashboardToggleEditMode;
    private notifyDashboardUpdated;
    helpLinkIdForWidgetType(): string;
    addWidget($event: Event, layoutCtx?: DashboardPageLayoutContext): void;
    onAddWidgetClosed(): void;
    detailsDrawerOpened(): void;
    detailsDrawerClosed(): void;
    private focusEditingWidget;
    private addWidgetToLayout;
    private isAddingToScadaLayout;
    private selectTargetLayout;
    private addWidgetToDashboard;
    addWidgetFromType(widget: WidgetInfo): void;
    onRevertWidgetEdit(): void;
    saveWidget(): void;
    onEditWidgetClosed(): void;
    editWidget($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    showLayoutConfigInEdit(layoutCtx: DashboardPageLayoutContext): boolean;
    replaceReferenceWithWidgetCopy($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    copyWidget($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    copyWidgetReference($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    copyWidgetsReference($event: Event, layoutCtx: DashboardPageLayoutContext, widgets: Widget[]): void;
    pasteWidgetDimensions($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    pasteWidgetStyle($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    copyWidgets($event: Event, layoutCtx: DashboardPageLayoutContext, widgets: Widget[]): void;
    pasteWidget($event: Event, layoutCtx: DashboardPageLayoutContext, pos: WidgetPosition): void;
    private selectPastedWidgets;
    private scadaKeyboardPastePosition;
    pasteWidgetReference($event: Event, layoutCtx: DashboardPageLayoutContext, pos: WidgetPosition): void;
    removeWidget($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    removeWidgets($event: Event, layoutCtx: DashboardPageLayoutContext, widgets: Widget[]): void;
    moveWidgetToLayer(layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    moveWidgetsToLayer(layoutCtx: DashboardPageLayoutContext, widgets: Widget[]): void;
    changeWidgetLayer(layoutCtx: DashboardPageLayoutContext, widget: Widget, mode: 'front' | 'back' | 'forward' | 'backward'): void;
    private renormalizeLayerZOrders;
    exportWidget($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget, widgetTitle: string): void;
    dashboardMouseDown($event: Event, layoutCtx: DashboardPageLayoutContext): void;
    widgetClicked($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    widgetMouseDown($event: Event, layoutCtx: DashboardPageLayoutContext, widget: Widget): void;
    prepareDashboardContextMenu(layoutCtx: DashboardPageLayoutContext): Array<DashboardContextMenuItem>;
    private contextMenuTargets;
    prepareWidgetContextMenu(layoutCtx: DashboardPageLayoutContext, widget: Widget, isReference: boolean): Array<WidgetContextMenuItem>;
    clearSelectedWidgetBundle(): void;
    editWidgetsTypesToDisplay($event: Event): void;
    updateDashboardImage($event: Event): void;
    toggleVersionControl($event: Event, versionControlButton: MatButton): void;
    get showMainLayoutFiller(): boolean;
    get currentBreakpointValue(): string;
    private parseBreakpointsResponse;
    private isMobileSize;
    static ɵfac: i0.ɵɵFactoryDeclaration<DashboardPageComponent, [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, { optional: true; }, null, null, null, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DashboardPageComponent, "tb-dashboard-page", never, { "embedded": { "alias": "embedded"; "required": false; }; "currentState": { "alias": "currentState"; "required": false; }; "hideToolbar": { "alias": "hideToolbar"; "required": false; }; "syncStateWithQueryParam": { "alias": "syncStateWithQueryParam"; "required": false; }; "dashboard": { "alias": "dashboard"; "required": false; }; "parentDashboard": { "alias": "parentDashboard"; "required": false; }; "popoverComponent": { "alias": "popoverComponent"; "required": false; }; "parentAliasController": { "alias": "parentAliasController"; "required": false; }; }, {}, never, never, false, never>;
}
