import { ElementRef, NgZone, OnInit, ViewContainerRef } from '@angular/core';
import { DragRef, Point } from '@angular/cdk/drag-drop';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { Router } from '@angular/router';
import { DialogComponent } from '@shared/components/dialog.component';
import { Dashboard } from '@shared/models/dashboard.models';
import { IDashboardComponent } from '@home/models/dashboard-component.models';
import { DialogGeometry } from '@home/components/widget/dialog/embed-dashboard-dialog-token';
import * as i0 from "@angular/core";
export interface EmbedDashboardDialogData {
    dashboard: Dashboard;
    state: string;
    title: string;
    hideToolbar: boolean;
    width?: number;
    height?: number;
    movable?: boolean;
    autoHideHeader?: boolean;
    geometryKey?: string;
    savedGeometry?: DialogGeometry;
    parentDashboard?: IDashboardComponent;
}
export declare class EmbedDashboardDialogComponent extends DialogComponent<EmbedDashboardDialogComponent> implements OnInit {
    protected store: Store<AppState>;
    protected router: Router;
    data: EmbedDashboardDialogData;
    dialogRef: MatDialogRef<EmbedDashboardDialogComponent>;
    private elementRef;
    private zone;
    dashboardContentContainer: ViewContainerRef;
    private drag;
    resizeDirections: string[];
    private static readonly minWidth;
    private static readonly minHeight;
    private static readonly minVisible;
    dashboard: Dashboard;
    state: string;
    title: string;
    hideToolbar: boolean;
    movable: boolean;
    autoHideHeader: boolean;
    parentDashboard: IDashboardComponent;
    dialogStyle: any;
    constructor(store: Store<AppState>, router: Router, data: EmbedDashboardDialogData, dialogRef: MatDialogRef<EmbedDashboardDialogComponent>, elementRef: ElementRef<HTMLElement>, zone: NgZone);
    ngOnInit(): void;
    dragConstrainPosition: (pointer: Point, dragRef: DragRef, dimensions: DOMRect, pickup: Point) => Point;
    startResize(event: PointerEvent, dir: string): void;
    private saveGeometry;
    bringToFront(): void;
    close(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EmbedDashboardDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EmbedDashboardDialogComponent, "tb-embed-dashboard-dialog", never, {}, {}, never, never, false, never>;
}
