import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityTableColumn, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CustomerService } from '@core/http/customer.service';
import { TenantService } from '@core/http/tenant.service';
import { BroadcastService } from '@core/services/broadcast.service';
import { MatDialog } from '@angular/material/dialog';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import { Edge, EdgeInfo } from '@shared/models/edge.models';
import { EdgeService } from '@core/http/edge.service';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class EdgesTableConfigResolver {
    private store;
    private broadcast;
    private edgeService;
    private customerService;
    private tenantService;
    private homeDialogs;
    private translate;
    private datePipe;
    private router;
    private dialog;
    private permissionService;
    private readonly config;
    private customerId;
    constructor(store: Store<AppState>, broadcast: BroadcastService, edgeService: EdgeService, customerService: CustomerService, tenantService: TenantService, homeDialogs: HomeDialogsService, translate: TranslateService, datePipe: DatePipe, router: Router, dialog: MatDialog, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<EdgeInfo>>;
    configureColumns(edgeScope: string): Array<EntityTableColumn<EdgeInfo>>;
    configureEntityFunctions(edgeScope: string): void;
    configureCellActions(edgeScope: string): Array<CellActionDescriptor<EdgeInfo>>;
    configureGroupActions(edgeScope: string): Array<GroupActionDescriptor<EdgeInfo>>;
    configureAddActions(edgeScope: string): Array<HeaderActionDescriptor>;
    importEdges($event: Event): void;
    private openEdge;
    openEdgeEntitiesByType($event: Event, edge: Edge, entityType: EntityType): void;
    syncEdge($event: any, edge: any): void;
    addEdge(): void;
    openInstructions($event: Event, edge: EdgeInfo, afterAdd?: boolean, upgradeAvailable?: boolean): void;
    onEdgeAction(action: EntityAction<EdgeInfo>, config: EntityTableConfig<EdgeInfo>): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<EdgesTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<EdgesTableConfigResolver>;
}
