import { GetValueSettings, SetValueSettings } from '@shared/models/action-widget-settings.models';
import { BackgroundSettings } from '@shared/models/widget-settings.models';
import { ThemeAwareColor } from '@shared/models/theme-color.models';
export interface PidControlWidgetSettings {
    title: string;
    pvUnits: string;
    spUnits: string;
    opUnits: string;
    decimals: number;
    pvMin: number;
    pvMax: number;
    showTuning: boolean;
    showFormula: boolean;
    pvValue: GetValueSettings<number>;
    spValue: GetValueSettings<number>;
    spSet: SetValueSettings;
    opValue: GetValueSettings<number>;
    opSet: SetValueSettings;
    autoValue: GetValueSettings<boolean>;
    autoSet: SetValueSettings;
    opMaxValue: GetValueSettings<number>;
    opMinValue: GetValueSettings<number>;
    disabledState: GetValueSettings<boolean>;
    pGainValue: GetValueSettings<number>;
    pGainSet: SetValueSettings;
    iTimeValue: GetValueSettings<number>;
    iTimeSet: SetValueSettings;
    dTimeValue: GetValueSettings<number>;
    dTimeSet: SetValueSettings;
    dGainValue: GetValueSettings<number>;
    dGainSet: SetValueSettings;
    actionValue: GetValueSettings<boolean>;
    actionSet: SetValueSettings;
    derivModeValue: GetValueSettings<boolean>;
    derivModeSet: SetValueSettings;
    gainModeValue: GetValueSettings<boolean>;
    gainModeSet: SetValueSettings;
    interlockValue: GetValueSettings<boolean>;
    interlockSet: SetValueSettings;
    pvColor: ThemeAwareColor;
    spColor: ThemeAwareColor;
    opColor: ThemeAwareColor;
    background: BackgroundSettings;
    padding: string;
}
export declare const pidControlDefaultSettings: PidControlWidgetSettings;
