import { ChangeDetectorRef, OnDestroy, OnInit } from '@angular/core';
import { BasicActionWidgetComponent } from '@home/components/widget/lib/action/action-widget.models';
import { PidControlWidgetSettings } from '@home/components/widget/lib/rpc/pid-control-widget.models';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { Observable } from 'rxjs';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class PidControlWidgetComponent extends BasicActionWidgetComponent implements OnInit, OnDestroy {
    protected imagePipe: ImagePipe;
    protected sanitizer: DomSanitizer;
    protected cd: ChangeDetectorRef;
    settings: PidControlWidgetSettings;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    padding: string;
    title: string;
    pvUnits: string;
    spUnits: string;
    opUnits: string;
    decimals: number;
    pvMin: number;
    pvMax: number;
    pvColor: string;
    spColor: string;
    opColor: string;
    pvTicks: Array<{
        pos: number;
        label: string;
    }>;
    opTicks: Array<{
        pos: number;
        label: string;
    }>;
    private themeSub;
    tab: 'op' | 'tune';
    showTuning: boolean;
    showFormula: boolean;
    pv: number;
    sp: number;
    op: number;
    auto: boolean;
    opMax: number;
    opMin: number;
    disabled: boolean;
    opError: string;
    pGain: number;
    iTime: number;
    dTime: number;
    dGain: number;
    action: boolean;
    derivMode: boolean;
    gainMode: boolean;
    interlock: boolean;
    private spSetter;
    private opSetter;
    private autoSetter;
    private pGainSetter;
    private iTimeSetter;
    private dTimeSetter;
    private dGainSetter;
    private actionSetter;
    private derivModeSetter;
    private gainModeSetter;
    private interlockSetter;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, cd: ChangeDetectorRef);
    ngOnInit(): void;
    setTab(tab: 'op' | 'tune'): void;
    commitTune(prop: 'pGain' | 'iTime' | 'dTime' | 'dGain', raw: any): void;
    setFlag(prop: 'action' | 'derivMode' | 'gainMode' | 'interlock', value: boolean): void;
    setMode(auto: boolean): void;
    commitSp(raw: any): void;
    onOpInput(raw: any): void;
    commitOp(raw: any): void;
    private opRangeMsg;
    fmt(v: number): string;
    /** Build evenly-spaced scale ticks (bottom→top) for the ruler beside a bar. */
    private makeTicks;
    pct(v: number, lo: number, hi: number): number;
    cannotEdit(): boolean;
    /** Tuning tab is only available to users who can write to the device. */
    protected onWritePermissionChanged(): void;
    ngOnDestroy(): void;
    private applyColors;
    private set;
    private toNum;
    static ɵfac: i0.ɵɵFactoryDeclaration<PidControlWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PidControlWidgetComponent, "tb-pid-control-widget", never, {}, {}, never, never, false, never>;
}
