import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { CellActionDescriptor, EntityTableColumn, EntityTableConfig, GroupActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ReportService } from '@core/http/report.service';
import { DialogService } from '@core/services/dialog.service';
import { MatDialog } from '@angular/material/dialog';
import { PermissionService } from '@core/services/permission.service';
import { ReportTemplate } from '@home/pages/reporting/models/report.models';
import * as i0 from "@angular/core";
export declare class ReportTemplatesTableConfigResolver {
    private store;
    private router;
    private reportService;
    private dialogService;
    private translate;
    private datePipe;
    private dialog;
    private permissionService;
    private readonly config;
    constructor(store: Store<AppState>, router: Router, reportService: ReportService, dialogService: DialogService, translate: TranslateService, datePipe: DatePipe, dialog: MatDialog, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<ReportTemplate>>;
    configureColumns(): Array<EntityTableColumn<ReportTemplate>>;
    private getTemplateTypeLabel;
    private getFormatLabel;
    configureEntityFunctions(): void;
    configureGroupActions(): Array<GroupActionDescriptor<ReportTemplate>>;
    exportSelectedTemplates($event: Event, templates: ReportTemplate[]): void;
    configureCellActions(): Array<CellActionDescriptor<ReportTemplate>>;
    editTemplate($event: Event, template: ReportTemplate): void;
    configureAddActions(): Array<any>;
    createTemplate(): Observable<ReportTemplate>;
    importTemplate(): void;
    private validateImportedTemplate;
    scheduleReport($event: Event, template: ReportTemplate): void;
    exportTemplate($event: Event, template: ReportTemplate): void;
    openTemplate($event: Event, template: ReportTemplate): void;
    onTemplateAction(action: EntityAction<ReportTemplate>): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportTemplatesTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<ReportTemplatesTableConfigResolver>;
}
