import { ChangeDetectorRef, ElementRef, OnDestroy } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '@home/components/entity/entity.component';
import { FormControl, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { ToggleHeaderOption } from '@shared/components/toggle-header.component';
import { CustomerService } from '@core/http/customer.service';
import { Customer } from '@shared/models/customer.model';
import { Observable } from 'rxjs';
import { ReportTemplate, ReportFormat, ReportTemplateType } from '@home/pages/reporting/models/report.models';
import * as i0 from "@angular/core";
export declare class ReportTemplateComponent extends EntityComponent<ReportTemplate> implements OnDestroy {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: ReportTemplate;
    protected entitiesTableConfigValue: EntityTableConfig<ReportTemplate>;
    fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    private customerService;
    templateTypes: ReportTemplateType[];
    formats: (ReportFormat.PDF | ReportFormat.CSV | ReportFormat.XLSX | ReportFormat.ODS | ReportFormat.SCRIPT)[];
    formatOptions: ToggleHeaderOption[];
    typeOptions: ToggleHeaderOption[];
    ownerInput: ElementRef<HTMLInputElement>;
    currentUserEmail: string;
    ownerSearchControl: FormControl<string | Customer>;
    filteredOwners: Observable<Customer[]>;
    private selectedOwner;
    private destroy$;
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: ReportTemplate, entitiesTableConfigValue: EntityTableConfig<ReportTemplate>, fb: UntypedFormBuilder, cd: ChangeDetectorRef, customerService: CustomerService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    private initOwnerAutocomplete;
    private tenantOwnerOption;
    private fetchCustomers;
    displayOwnerFn: (value: Customer | string) => string;
    clearOwnerSelection(event: Event): void;
    hideDelete(): boolean;
    buildForm(entity: ReportTemplate): UntypedFormGroup;
    updateForm(entity: ReportTemplate): void;
    getTemplateTypeLabel(type: ReportTemplateType): string;
    getFormatLabel(format: ReportFormat): string;
    onTemplateIdCopied($event: any): void;
    isSubReport(): boolean;
    prepareFormValue(formValue: any): any;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportTemplateComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ReportTemplateComponent, "tb-report-template", never, {}, {}, never, never, false, never>;
}
