import { OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { NestedTreeControl } from '@angular/cdk/tree';
import { MatTreeNestedDataSource } from '@angular/material/tree';
import { DatePipe } from '@angular/common';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityGroupService } from '@core/http/entity-group.service';
import { Customer } from '@shared/models/customer.model';
import { EntityGroup, EntityGroupType } from '@shared/models/entity-group.model';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { CustomerService } from '@core/http/customer.service';
import { EntityGroupTableConfigService } from '@home/services/entity-group-table-config.service';
import * as i0 from "@angular/core";
export type HierarchyNodeType = 'customerGroup' | 'customer' | 'groupCategory' | 'entityGroup';
export interface HierarchyNode {
    id: string;
    type: HierarchyNodeType;
    name: string;
    icon: string;
    children: HierarchyNode[];
    loaded: boolean;
    loading: boolean;
    entityGroup?: EntityGroup;
    customer?: Customer;
    groupType?: EntityGroupType;
    parentCustomer?: Customer;
}
export declare class CustomerHierarchyComponent implements OnInit, OnDestroy {
    private entityGroupService;
    private customerService;
    private translate;
    private datePipe;
    private dialog;
    private store;
    private cd;
    private groupTableService;
    private destroy$;
    treeControl: NestedTreeControl<HierarchyNode, HierarchyNode>;
    dataSource: MatTreeNestedDataSource<HierarchyNode>;
    loading: boolean;
    selectedNode: HierarchyNode;
    hierarchyGroupsConfig: EntityTableConfig<any>;
    treePanelVisible: boolean;
    constructor(entityGroupService: EntityGroupService, customerService: CustomerService, translate: TranslateService, datePipe: DatePipe, dialog: MatDialog, store: Store<AppState>, cd: ChangeDetectorRef, groupTableService: EntityGroupTableConfigService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    hasChild: (_: number, node: HierarchyNode) => boolean;
    toggleNode(node: HierarchyNode): void;
    toggleTreePanel(): void;
    onNodeSelect(node: HierarchyNode): void;
    navigateUp(): void;
    private getTopLevelOwnerId;
    private loadCustomerGroups;
    private loadChildren;
    private loadCustomerGroupMembers;
    private loadCustomerCategories;
    private loadEntityGroups;
    private loadCustomerGroupChildren;
    private loadCustomerEntityGroupMembers;
    private buildDefaultCustomerGroupsTable;
    private buildGroupsTableConfig;
    private buildMembersTableConfig;
    private buildCustomerGroupMembersTableConfig;
    private refreshTree;
    private findParentNode;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomerHierarchyComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomerHierarchyComponent, "tb-customer-hierarchy", never, {}, {}, never, never, false, never>;
}
