import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe, Location } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Customer } from '@app/shared/models/customer.model';
import { CustomerService } from '@app/core/http/customer.service';
import { TenantService } from '@core/http/tenant.service';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import { Observable } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';
import { EntityGroupService } from '@core/http/entity-group.service';
import { CustomerNavigationService } from '@core/services/customer-navigation.service';
import { PermissionService } from '@core/services/permission.service';
import * as i0 from "@angular/core";
export declare class CustomersTableConfigResolver {
    private customerService;
    private tenantService;
    private homeDialogs;
    private translate;
    private datePipe;
    private router;
    private location;
    private store;
    private dialog;
    private entityGroupService;
    private customerNavService;
    private permissionService;
    private readonly config;
    /** Title of the customer currently shown (used when pushing to nav stack). */
    private currentCustomerTitle;
    constructor(customerService: CustomerService, tenantService: TenantService, homeDialogs: HomeDialogsService, translate: TranslateService, datePipe: DatePipe, router: Router, location: Location, store: Store<AppState>, dialog: MatDialog, entityGroupService: EntityGroupService, customerNavService: CustomerNavigationService, permissionService: PermissionService);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<Customer>>;
    configureColumns(includeSubCustomers: boolean): void;
    private enrichCustomers;
    private openCustomer;
    manageCustomerUsers($event: Event, customer: Customer): void;
    manageCustomerAssets($event: Event, customer: Customer): void;
    manageCustomerDevices($event: Event, customer: Customer): void;
    manageCustomerDashboards($event: Event, customer: Customer): void;
    manageCustomerEntityViews($event: Event, customer: Customer): void;
    manageSubCustomers($event: Event, customer: Customer): void;
    manageCustomerEdges($event: Event, customer: Customer): void;
    manageOwnerAndGroups($event: Event, customer: Customer): void;
    onCustomerAction(action: EntityAction<Customer>, config: EntityTableConfig<Customer>): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomersTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<CustomersTableConfigResolver>;
}
