import { ChangeDetectorRef, OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { ReportHeaderWidgetSettings } from './report-header-widget.models';
import { WidgetContext } from '@home/models/widget-component.models';
import { Observable } from 'rxjs';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import { DatePipe } from '@angular/common';
import * as i0 from "@angular/core";
export declare class ReportHeaderWidgetComponent implements OnInit, OnDestroy {
    private imagePipe;
    private sanitizer;
    private datePipe;
    private cd;
    settings: ReportHeaderWidgetSettings;
    private themeChangeSubscription;
    ctx: WidgetContext;
    widgetTitlePanel: TemplateRef<any>;
    backgroundStyle$: Observable<ComponentStyle>;
    padding: string;
    title: string;
    titleStyle: ComponentStyle;
    titleAlignment: string;
    showLogo: boolean;
    logoUrl: string;
    logoPosition: string;
    logoMaxHeight: number;
    showDate: boolean;
    formattedDate: string;
    dateStyle: ComponentStyle;
    showPageNumber: boolean;
    pageNumberText: string;
    pageNumberStyle: ComponentStyle;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, datePipe: DatePipe, cd: ChangeDetectorRef);
    ngOnInit(): void;
    private applyThemeColors;
    ngOnDestroy(): void;
    onInit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportHeaderWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ReportHeaderWidgetComponent, "tb-report-header-widget", never, { "ctx": { "alias": "ctx"; "required": false; }; "widgetTitlePanel": { "alias": "widgetTitlePanel"; "required": false; }; }, {}, never, never, false, never>;
}
