import { AfterViewInit, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { CdkDragDrop } from '@angular/cdk/drag-drop';
import { TranslateService } from '@ngx-translate/core';
import { DialogService } from '@core/services/dialog.service';
import { EntityGroup, EntityGroupAction, ActionSourceType, EntityGroupActionType } from '@shared/models/entity-group.model';
import * as i0 from "@angular/core";
export declare class EntityGroupActionsComponent implements OnInit, OnChanges, AfterViewInit {
    private dialog;
    private translate;
    private dialogService;
    entityGroup: EntityGroup;
    isEdit: boolean;
    configChanged: EventEmitter<EntityGroupAction[]>;
    displayedColumns: string[];
    dataSource: MatTableDataSource<EntityGroupAction, MatPaginator>;
    searchMode: boolean;
    searchText: string;
    sort: MatSort;
    paginator: MatPaginator;
    private actions;
    constructor(dialog: MatDialog, translate: TranslateService, dialogService: DialogService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    private loadActions;
    getSourceLabel(source: ActionSourceType): string;
    getTypeLabel(type: EntityGroupActionType): string;
    toggleSearch(): void;
    applyFilter(filterValue: string): void;
    addAction(): void;
    editAction($event: Event, action: EntityGroupAction, index: number): void;
    deleteAction($event: Event, action: EntityGroupAction, index: number): void;
    dropAction(event: CdkDragDrop<EntityGroupAction[]>): void;
    private emitChange;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityGroupActionsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityGroupActionsComponent, "tb-entity-group-actions", never, { "entityGroup": { "alias": "entityGroup"; "required": false; }; "isEdit": { "alias": "isEdit"; "required": false; }; }, { "configChanged": "configChanged"; }, never, never, false, never>;
}
